## 04_02 Preparing Data for Classification

# Books

In [108]:
#load_features
tfidf_books = pd.read_csv("tfidf_books.csv").drop(columns=['Unnamed: 0'])
struct_books = pd.read_csv("struct_books.csv").drop(columns=['Unnamed: 0'])
inq_books = pd.read_csv("inq_books.csv").drop(columns=['Unnamed: 0'])[:1324]
liwc_books = pd.read_csv("liwc_books.csv").drop(columns=['Unnamed: 0'])
galc_books = pd.read_csv("galc_books.csv").drop(columns=['Unnamed: 0'])

In [67]:
#load_classes
classes = pd.read_csv("classes_books.csv").drop(columns=['Unnamed: 0'])

In [120]:
books_features = {"tf-idf":tfidf_books,"struct_books":struct_books,"inq_books":inq_books,"liwc_books":liwc_books,"galc_books":galc_books}

# 1 feature

In [126]:
for i,k in books_features.items():
    print(i)
    print("---")
    features = k
    extract_classify_test(features,classes)

tf-idf
---
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[153   9]
 [131  38]]

 Prediction Accuracy :  0.5770392749244713
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVM
Confusion Matrix : 
[[119  43]
 [ 46 123]]

 Prediction Accuracy :  0.7311178247734139
------------------------
Decision Tree
Confusion Matrix : 
[[114  48]
 [ 58 111]]

 Prediction Accuracy :  0.6797583081570997
------------------------
Random Forest
Confusion Matrix : 
[[112  50]
 [ 40 129]]

 Prediction Accuracy :  0.7280966767371602
------------------------
NN
Confusion Matrix : 
[[162   0]
 [169   0]]

 Prediction Accuracy :  0.48942598187311176
------------------------
struct_books
---
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[118  44]
 [110  59]]

 Prediction Accuracy :  0.5347432024169184
------------------------
SVM
Confusion Matrix : 
[[ 82  80]
 [ 31 138]]

 Prediction Accuracy :  0.6646525679758308
------------------------
Decision Tree
Confusion Matrix : 
[[103  59]
 [ 61 108]]

 Prediction Accuracy :  0.6374622356495468
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Random Forest
Confusion Matrix : 
[[122  40]
 [ 63 106]]

 Prediction Accuracy :  0.6888217522658611
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NN
Confusion Matrix : 
[[127  35]
 [ 63 106]]

 Prediction Accuracy :  0.7039274924471299
------------------------
inq_books
---
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[123  39]
 [117  52]]

 Prediction Accuracy :  0.5287009063444109
------------------------
SVM
Confusion Matrix : 
[[ 85  77]
 [ 19 150]]

 Prediction Accuracy :  0.7099697885196374
------------------------
Decision Tree
Confusion Matrix : 
[[ 95  67]
 [ 53 116]]

 Prediction Accuracy :  0.6374622356495468
------------------------
Random Forest
Confusion Matrix : 
[[106  56]
 [ 28 141]]

 Prediction Accuracy :  0.7462235649546828
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NN
Confusion Matrix : 
[[117  45]
 [ 47 122]]

 Prediction Accuracy :  0.7220543806646526
------------------------
liwc_books
---
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[134  28]
 [127  42]]

 Prediction Accuracy :  0.5317220543806647
------------------------
SVM
Confusion Matrix : 
[[ 99  63]
 [ 29 140]]

 Prediction Accuracy :  0.7220543806646526
------------------------
Decision Tree
Confusion Matrix : 
[[109  53]
 [ 65 104]]

 Prediction Accuracy :  0.6435045317220544
------------------------
Random Forest
Confusion Matrix : 
[[117  45]
 [ 50 119]]

 Prediction Accuracy :  0.7129909365558912
------------------------
NN
Confusion Matrix : 
[[162   0]
 [169   0]]

 Prediction Accuracy :  0.48942598187311176
------------------------
galc_books
---
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[136  26]
 [151  18]]

 Prediction Accuracy 

/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Random Forest
Confusion Matrix : 
[[ 70  92]
 [ 24 145]]

 Prediction Accuracy :  0.649546827794562
------------------------
NN
Confusion Matrix : 
[[ 65  97]
 [ 30 139]]

 Prediction Accuracy :  0.6163141993957704
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


# 2 features

In [146]:
comb_books_2 = combinations(books_features, 2) 
for i,t in enumerate(comb_books_2):
    print(t)
    cols_to_use = books_features[t[1]].columns.difference(books_features[t[0]].columns)
    features = books_features[t[0]].join(books_features[t[1]][cols_to_use])
    extract_classify_test(features,classes)

('tf-idf', 'struct_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NB
Confusion Matrix : 
[[155   7]
 [137  32]]

 Prediction Accuracy :  0.5649546827794562
------------------------
SVM
Confusion Matrix : 
[[118  44]
 [ 45 124]]

 Prediction Accuracy :  0.7311178247734139
------------------------
Decision Tree
Confusion Matrix : 
[[118  44]
 [ 49 120]]

 Prediction Accuracy :  0.7190332326283988
------------------------
Random Forest
Confusion Matrix : 
[[119  43]
 [ 45 124]]

 Prediction Accuracy :  0.7341389728096677
------------------------
NN
Confusion Matrix : 
[[128  34]
 [ 54 115]]

 Prediction Accuracy :  0.7341389728096677
------------------------
('tf-idf', 'inq_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Confusion Matrix : 
[[153   9]
 [131  38]]

 Prediction Accuracy :  0.5770392749244713
------------------------
SVM
Confusion Matrix : 
[[119  43]
 [ 46 123]]

 Prediction Accuracy :  0.7311178247734139
------------------------
Decision Tree
Confusion Matrix : 
[[118  44]
 [ 65 104]]

 Prediction Accuracy :  0.6706948640483383
------------------------
Random Forest
Confusion Matrix : 
[[112  50]
 [ 40 129]]

 Prediction Accuracy :  0.7280966767371602
------------------------
NN
Confusion Matrix : 
[[162   0]
 [169   0]]

 Prediction Accuracy :  0.48942598187311176
------------------------
('tf-idf', 'liwc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NB
Confusion Matrix : 
[[156   6]
 [140  29]]

 Prediction Accuracy :  0.5589123867069486
------------------------
SVM
Confusion Matrix : 
[[118  44]
 [ 40 129]]

 Prediction Accuracy :  0.7462235649546828
------------------------
Decision Tree
Confusion Matrix : 
[[108  54]
 [ 52 117]]

 Prediction Accuracy :  0.6797583081570997
------------------------
Random Forest
Confusion Matrix : 
[[113  49]
 [ 38 131]]

 Prediction Accuracy :  0.7371601208459214
------------------------
NN
Confusion Matrix : 
[[131  31]
 [ 55 114]]

 Prediction Accuracy :  0.7401812688821753
------------------------
('tf-idf', 'galc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NB
Confusion Matrix : 
[[157   5]
 [134  35]]

 Prediction Accuracy :  0.5800604229607251
------------------------
SVM
Confusion Matrix : 
[[115  47]
 [ 38 131]]

 Prediction Accuracy :  0.743202416918429
------------------------
Decision Tree
Confusion Matrix : 
[[115  47]
 [ 53 116]]

 Prediction Accuracy :  0.6978851963746223
------------------------
Random Forest
Confusion Matrix : 
[[112  50]
 [ 37 132]]

 Prediction Accuracy :  0.7371601208459214
------------------------
NN
Confusion Matrix : 
[[162   0]
 [169   0]]

 Prediction Accuracy :  0.48942598187311176
------------------------
('struct_books', 'inq_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[ 99  63]
 [ 60 109]]

 Prediction Accuracy :  0.6283987915407855
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVM
Confusion Matrix : 
[[116  46]
 [ 20 149]]

 Prediction Accuracy :  0.8006042296072508
------------------------
Decision Tree
Confusion Matrix : 
[[116  46]
 [ 46 123]]

 Prediction Accuracy :  0.7220543806646526
------------------------
Random Forest
Confusion Matrix : 
[[118  44]
 [ 27 142]]

 Prediction Accuracy :  0.7854984894259819
------------------------
NN
Confusion Matrix : 
[[162   0]
 [169   0]]

 Prediction Accuracy :  0.48942598187311176
------------------------
('struct_books', 'liwc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[113  49]
 [ 69 100]]

 Prediction Accuracy :  0.6435045317220544
------------------------
SVM
Confusion Matrix : 
[[103  59]
 [ 31 138]]

 Prediction Accuracy :  0.7280966767371602
------------------------
Decision Tree
Confusion Matrix : 
[[103  59]
 [ 63 106]]

 Prediction Accuracy :  0.6314199395770392
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Random Forest
Confusion Matrix : 
[[119  43]
 [ 54 115]]

 Prediction Accuracy :  0.7069486404833837
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NN
Confusion Matrix : 
[[122  40]
 [ 51 118]]

 Prediction Accuracy :  0.7250755287009063
------------------------
('struct_books', 'galc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[115  47]
 [ 98  71]]

 Prediction Accuracy :  0.5619335347432024
------------------------
SVM
Confusion Matrix : 
[[ 92  70]
 [ 29 140]]

 Prediction Accuracy :  0.7009063444108762
------------------------
Decision Tree
Confusion Matrix : 
[[105  57]
 [ 65 104]]

 Prediction Accuracy :  0.6314199395770392
------------------------
Random Forest
Confusion Matrix : 
[[121  41]
 [ 56 113]]

 Prediction Accuracy :  0.7069486404833837
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NN
Confusion Matrix : 
[[112  50]
 [ 52 117]]

 Prediction Accuracy :  0.6918429003021148
------------------------
('inq_books', 'liwc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[127  35]
 [113  56]]

 Prediction Accuracy :  0.552870090634441
------------------------
SVM
Confusion Matrix : 
[[121  41]
 [ 26 143]]

 Prediction Accuracy :  0.797583081570997
------------------------
Decision Tree
Confusion Matrix : 
[[115  47]
 [ 47 122]]

 Prediction Accuracy :  0.716012084592145
------------------------
Random Forest
Confusion Matrix : 
[[134  28]
 [ 36 133]]

 Prediction Accuracy :  0.8066465256797583
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NN
Confusion Matrix : 
[[121  41]
 [ 46 123]]

 Prediction Accuracy :  0.7371601208459214
------------------------
('inq_books', 'galc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[ 96  66]
 [107  62]]

 Prediction Accuracy :  0.4773413897280967
------------------------
SVM
Confusion Matrix : 
[[100  62]
 [ 20 149]]

 Prediction Accuracy :  0.7522658610271903
------------------------
Decision Tree
Confusion Matrix : 
[[102  60]
 [ 50 119]]

 Prediction Accuracy :  0.6676737160120846
------------------------
Random Forest
Confusion Matrix : 
[[101  61]
 [ 29 140]]

 Prediction Accuracy :  0.7280966767371602
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NN
Confusion Matrix : 
[[108  54]
 [ 39 130]]

 Prediction Accuracy :  0.7190332326283988
------------------------
('liwc_books', 'galc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[124  38]
 [135  34]]

 Prediction Accuracy :  0.4773413897280967
------------------------
SVM
Confusion Matrix : 
[[107  55]
 [ 29 140]]

 Prediction Accuracy :  0.7462235649546828
------------------------
Decision Tree
Confusion Matrix : 
[[106  56]
 [ 59 110]]

 Prediction Accuracy :  0.6525679758308157
------------------------
Random Forest
Confusion Matrix : 
[[117  45]
 [ 45 124]]

 Prediction Accuracy :  0.7280966767371602
------------------------
NN
Confusion Matrix : 
[[162   0]
 [169   0]]

 Prediction Accuracy :  0.48942598187311176
------------------------


# 3 features

In [148]:
comb_books_3 = combinations(books_features, 3) 
for i,t in enumerate(comb_books_3):
    print(t)
    cols_to_use = books_features[t[1]].columns.difference(books_features[t[0]].columns)
    features = books_features[t[0]].join(books_features[t[1]][cols_to_use])
    cols_to_use = books_features[t[2]].columns.difference(features.columns)
    features = features.join(books_features[t[2]][cols_to_use])
    extract_classify_test(features,classes)

('tf-idf', 'struct_books', 'inq_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NB
Confusion Matrix : 
[[155   7]
 [137  32]]

 Prediction Accuracy :  0.5649546827794562
------------------------
SVM
Confusion Matrix : 
[[118  44]
 [ 45 124]]

 Prediction Accuracy :  0.7311178247734139
------------------------
Decision Tree
Confusion Matrix : 
[[121  41]
 [ 51 118]]

 Prediction Accuracy :  0.7220543806646526
------------------------
Random Forest
Confusion Matrix : 
[[119  43]
 [ 45 124]]

 Prediction Accuracy :  0.7341389728096677
------------------------
NN
Confusion Matrix : 
[[128  34]
 [ 54 115]]

 Prediction Accuracy :  0.7341389728096677
------------------------
('tf-idf', 'struct_books', 'liwc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NB
Confusion Matrix : 
[[157   5]
 [141  28]]

 Prediction Accuracy :  0.5589123867069486
------------------------
SVM
Confusion Matrix : 
[[116  46]
 [ 41 128]]

 Prediction Accuracy :  0.7371601208459214
------------------------
Decision Tree
Confusion Matrix : 
[[113  49]
 [ 50 119]]

 Prediction Accuracy :  0.7009063444108762
------------------------
Random Forest
Confusion Matrix : 
[[113  49]
 [ 41 128]]

 Prediction Accuracy :  0.7280966767371602
------------------------
NN
Confusion Matrix : 
[[  8 154]
 [  1 168]]

 Prediction Accuracy :  0.5317220543806647
------------------------
('tf-idf', 'struct_books', 'galc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NB
Confusion Matrix : 
[[157   5]
 [141  28]]

 Prediction Accuracy :  0.5589123867069486
------------------------
SVM
Confusion Matrix : 
[[116  46]
 [ 38 131]]

 Prediction Accuracy :  0.7462235649546828
------------------------
Decision Tree
Confusion Matrix : 
[[122  40]
 [ 61 108]]

 Prediction Accuracy :  0.6948640483383686
------------------------
Random Forest
Confusion Matrix : 
[[113  49]
 [ 36 133]]

 Prediction Accuracy :  0.743202416918429
------------------------
NN
Confusion Matrix : 
[[108  54]
 [ 39 130]]

 Prediction Accuracy :  0.7190332326283988
------------------------
('tf-idf', 'inq_books', 'liwc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NB
Confusion Matrix : 
[[156   6]
 [140  29]]

 Prediction Accuracy :  0.5589123867069486
------------------------
SVM
Confusion Matrix : 
[[118  44]
 [ 40 129]]

 Prediction Accuracy :  0.7462235649546828
------------------------
Decision Tree
Confusion Matrix : 
[[108  54]
 [ 50 119]]

 Prediction Accuracy :  0.6858006042296072
------------------------
Random Forest
Confusion Matrix : 
[[113  49]
 [ 38 131]]

 Prediction Accuracy :  0.7371601208459214
------------------------
NN
Confusion Matrix : 
[[131  31]
 [ 55 114]]

 Prediction Accuracy :  0.7401812688821753
------------------------
('tf-idf', 'inq_books', 'galc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NB
Confusion Matrix : 
[[157   5]
 [134  35]]

 Prediction Accuracy :  0.5800604229607251
------------------------
SVM
Confusion Matrix : 
[[115  47]
 [ 38 131]]

 Prediction Accuracy :  0.743202416918429
------------------------
Decision Tree
Confusion Matrix : 
[[113  49]
 [ 52 117]]

 Prediction Accuracy :  0.6948640483383686
------------------------
Random Forest
Confusion Matrix : 
[[112  50]
 [ 37 132]]

 Prediction Accuracy :  0.7371601208459214
------------------------
NN
Confusion Matrix : 
[[162   0]
 [169   0]]

 Prediction Accuracy :  0.48942598187311176
------------------------
('tf-idf', 'liwc_books', 'galc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NB
Confusion Matrix : 
[[158   4]
 [142  27]]

 Prediction Accuracy :  0.5589123867069486
------------------------
SVM
Confusion Matrix : 
[[116  46]
 [ 40 129]]

 Prediction Accuracy :  0.7401812688821753
------------------------
Decision Tree
Confusion Matrix : 
[[104  58]
 [ 52 117]]

 Prediction Accuracy :  0.6676737160120846
------------------------
Random Forest
Confusion Matrix : 
[[114  48]
 [ 40 129]]

 Prediction Accuracy :  0.7341389728096677
------------------------
NN
Confusion Matrix : 
[[110  52]
 [ 39 130]]

 Prediction Accuracy :  0.7250755287009063
------------------------
('struct_books', 'inq_books', 'liwc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[113  49]
 [ 67 102]]

 Prediction Accuracy :  0.649546827794562
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVM
Confusion Matrix : 
[[124  38]
 [ 26 143]]

 Prediction Accuracy :  0.8066465256797583
------------------------
Decision Tree
Confusion Matrix : 
[[111  51]
 [ 49 120]]

 Prediction Accuracy :  0.6978851963746223
------------------------
Random Forest
Confusion Matrix : 
[[131  31]
 [ 35 134]]

 Prediction Accuracy :  0.8006042296072508
------------------------
NN
Confusion Matrix : 
[[162   0]
 [169   0]]

 Prediction Accuracy :  0.48942598187311176
------------------------
('struct_books', 'inq_books', 'galc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[ 85  77]
 [ 61 108]]

 Prediction Accuracy :  0.5830815709969789
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVM
Confusion Matrix : 
[[116  46]
 [ 24 145]]

 Prediction Accuracy :  0.7885196374622356
------------------------
Decision Tree
Confusion Matrix : 
[[116  46]
 [ 44 125]]

 Prediction Accuracy :  0.7280966767371602
------------------------
Random Forest
Confusion Matrix : 
[[110  52]
 [ 26 143]]

 Prediction Accuracy :  0.7643504531722054
------------------------
NN
Confusion Matrix : 
[[162   0]
 [169   0]]

 Prediction Accuracy :  0.48942598187311176
------------------------
('struct_books', 'liwc_books', 'galc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[111  51]
 [ 80  89]]

 Prediction Accuracy :  0.6042296072507553
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVM
Confusion Matrix : 
[[105  57]
 [ 31 138]]

 Prediction Accuracy :  0.7341389728096677
------------------------
Decision Tree
Confusion Matrix : 
[[100  62]
 [ 64 105]]

 Prediction Accuracy :  0.6193353474320241
------------------------
Random Forest
Confusion Matrix : 
[[117  45]
 [ 53 116]]

 Prediction Accuracy :  0.7039274924471299
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NN
Confusion Matrix : 
[[121  41]
 [ 56 113]]

 Prediction Accuracy :  0.7069486404833837
------------------------
('inq_books', 'liwc_books', 'galc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[112  50]
 [111  58]]

 Prediction Accuracy :  0.513595166163142
------------------------
SVM
Confusion Matrix : 
[[119  43]
 [ 27 142]]

 Prediction Accuracy :  0.7885196374622356
------------------------
Decision Tree
Confusion Matrix : 
[[119  43]
 [ 47 122]]

 Prediction Accuracy :  0.7280966767371602
------------------------
Random Forest
Confusion Matrix : 
[[124  38]
 [ 32 137]]

 Prediction Accuracy :  0.7885196374622356
------------------------
NN
Confusion Matrix : 
[[128  34]
 [ 52 117]]

 Prediction Accuracy :  0.7401812688821753
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


# 4 Features

In [149]:
comb_books_4 = combinations(books_features, 4) 
for i,t in enumerate(comb_books_4):
    print(t)
    cols_to_use = books_features[t[1]].columns.difference(books_features[t[0]].columns)
    features = books_features[t[0]].join(books_features[t[1]][cols_to_use])
    cols_to_use = books_features[t[2]].columns.difference(features.columns)
    features = features.join(books_features[t[2]][cols_to_use])
    
    cols_to_use = books_features[t[3]].columns.difference(features.columns)
    features = features.join(books_features[t[3]][cols_to_use])
    
    extract_classify_test(features,classes)

('tf-idf', 'struct_books', 'inq_books', 'liwc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NB
Confusion Matrix : 
[[157   5]
 [141  28]]

 Prediction Accuracy :  0.5589123867069486
------------------------
SVM
Confusion Matrix : 
[[116  46]
 [ 41 128]]

 Prediction Accuracy :  0.7371601208459214
------------------------
Decision Tree
Confusion Matrix : 
[[119  43]
 [ 53 116]]

 Prediction Accuracy :  0.7099697885196374
------------------------
Random Forest
Confusion Matrix : 
[[113  49]
 [ 41 128]]

 Prediction Accuracy :  0.7280966767371602
------------------------
NN
Confusion Matrix : 
[[  8 154]
 [  1 168]]

 Prediction Accuracy :  0.5317220543806647
------------------------
('tf-idf', 'struct_books', 'inq_books', 'galc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NB
Confusion Matrix : 
[[157   5]
 [141  28]]

 Prediction Accuracy :  0.5589123867069486
------------------------
SVM
Confusion Matrix : 
[[116  46]
 [ 38 131]]

 Prediction Accuracy :  0.7462235649546828
------------------------
Decision Tree
Confusion Matrix : 
[[117  45]
 [ 63 106]]

 Prediction Accuracy :  0.6737160120845922
------------------------
Random Forest
Confusion Matrix : 
[[113  49]
 [ 36 133]]

 Prediction Accuracy :  0.743202416918429
------------------------
NN
Confusion Matrix : 
[[108  54]
 [ 39 130]]

 Prediction Accuracy :  0.7190332326283988
------------------------
('tf-idf', 'struct_books', 'liwc_books', 'galc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NB
Confusion Matrix : 
[[158   4]
 [144  25]]

 Prediction Accuracy :  0.552870090634441
------------------------
SVM
Confusion Matrix : 
[[115  47]
 [ 38 131]]

 Prediction Accuracy :  0.743202416918429
------------------------
Decision Tree
Confusion Matrix : 
[[113  49]
 [ 51 118]]

 Prediction Accuracy :  0.6978851963746223
------------------------
Random Forest
Confusion Matrix : 
[[114  48]
 [ 39 130]]

 Prediction Accuracy :  0.7371601208459214
------------------------
NN
Confusion Matrix : 
[[162   0]
 [169   0]]

 Prediction Accuracy :  0.48942598187311176
------------------------
('tf-idf', 'inq_books', 'liwc_books', 'galc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NB
Confusion Matrix : 
[[158   4]
 [142  27]]

 Prediction Accuracy :  0.5589123867069486
------------------------
SVM
Confusion Matrix : 
[[116  46]
 [ 40 129]]

 Prediction Accuracy :  0.7401812688821753
------------------------
Decision Tree
Confusion Matrix : 
[[105  57]
 [ 56 113]]

 Prediction Accuracy :  0.6586102719033232
------------------------
Random Forest
Confusion Matrix : 
[[114  48]
 [ 40 129]]

 Prediction Accuracy :  0.7341389728096677
------------------------
NN
Confusion Matrix : 
[[110  52]
 [ 39 130]]

 Prediction Accuracy :  0.7250755287009063
------------------------
('struct_books', 'inq_books', 'liwc_books', 'galc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[105  57]
 [ 65 104]]

 Prediction Accuracy :  0.6314199395770392
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVM
Confusion Matrix : 
[[121  41]
 [ 28 141]]

 Prediction Accuracy :  0.7915407854984894
------------------------
Decision Tree
Confusion Matrix : 
[[116  46]
 [ 51 118]]

 Prediction Accuracy :  0.7069486404833837
------------------------
Random Forest
Confusion Matrix : 
[[126  36]
 [ 32 137]]

 Prediction Accuracy :  0.7945619335347432
------------------------
NN
Confusion Matrix : 
[[124  38]
 [ 42 127]]

 Prediction Accuracy :  0.7583081570996979
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


# 5 Features

In [150]:
comb_books_5 = combinations(books_features, 5) 
for i,t in enumerate(comb_books_5):
    print(t)
    cols_to_use = books_features[t[1]].columns.difference(books_features[t[0]].columns)
    features = books_features[t[0]].join(books_features[t[1]][cols_to_use])
    cols_to_use = books_features[t[2]].columns.difference(features.columns)
    features = features.join(books_features[t[2]][cols_to_use])
    
    cols_to_use = books_features[t[3]].columns.difference(features.columns)
    features = features.join(books_features[t[3]][cols_to_use])
    
    cols_to_use = books_features[t[4]].columns.difference(features.columns)
    features = features.join(books_features[t[4]][cols_to_use])
    
    extract_classify_test(features,classes)

('tf-idf', 'struct_books', 'inq_books', 'liwc_books', 'galc_books')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


NB
Confusion Matrix : 
[[158   4]
 [144  25]]

 Prediction Accuracy :  0.552870090634441
------------------------
SVM
Confusion Matrix : 
[[115  47]
 [ 38 131]]

 Prediction Accuracy :  0.743202416918429
------------------------
Decision Tree
Confusion Matrix : 
[[102  60]
 [ 47 122]]

 Prediction Accuracy :  0.676737160120846
------------------------
Random Forest
Confusion Matrix : 
[[114  48]
 [ 39 130]]

 Prediction Accuracy :  0.7371601208459214
------------------------
NN
Confusion Matrix : 
[[162   0]
 [169   0]]

 Prediction Accuracy :  0.48942598187311176
------------------------


# Hotels

In [159]:
#load_features
tfidf_hotels = pd.read_csv("tfidf_hotels.csv").drop(columns=['Unnamed: 0'])
struct_hotels = pd.read_csv("struct_hotels.csv").drop(columns=['Unnamed: 0'])
inq_hotels = pd.read_csv("inq_hotels.csv").drop(columns=['Unnamed: 0'])[:1282]
liwc_hotels = pd.read_csv("liwc_hotels.csv").drop(columns=['Unnamed: 0'])
galc_hotels = pd.read_csv("galc_hotels.csv").drop(columns=['Unnamed: 0'])

In [162]:
#load_classes
hotels_classes = pd.read_csv("classes_hotels.csv")['helpfulness']

# 1-5 Features Combinations 

In [163]:
hotels_features = {"tf-idf":tfidf_hotels,"struct_hotels":struct_hotels,"inq_hotels":inq_hotels,"liwc_hotels":liwc_hotels,"galc_hotels":galc_hotels}

In [164]:
for i,k in hotels_features.items():
    print(i)
    print("---")
    features = k
    extract_classify_test(features,hotels_classes)

tf-idf
---
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[113  50]
 [ 82  76]]

 Prediction Accuracy :  0.5887850467289719
------------------------
SVM
Confusion Matrix : 
[[97 66]
 [63 95]]

 Prediction Accuracy :  0.5981308411214953
------------------------
Decision Tree
Confusion Matrix : 
[[97 66]
 [79 79]]

 Prediction Accuracy :  0.5482866043613707
------------------------
Random Forest
Confusion Matrix : 
[[ 98  65]
 [ 52 106]]

 Prediction Accuracy :  0.6355140186915887
------------------------
NN
Confusion Matrix : 
[[  0 163]
 [  0 158]]

 Prediction Accuracy :  0.49221183800623053
------------------------
struct_hotels
---
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[ 32 131]
 [ 20 138]]

 Prediction Accuracy :  0.5295950155763239
------------------------
SVM
Confusion Matrix : 
[[ 79  84]
 [ 35 123]]

 Prediction Accuracy :  0.629

/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


NN
Confusion Matrix : 
[[113  50]
 [ 55 103]]

 Prediction Accuracy :  0.6728971962616822
------------------------
inq_hotels
---
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[83 80]
 [66 92]]

 Prediction Accuracy :  0.5451713395638629
------------------------
SVM
Confusion Matrix : 
[[ 73  90]
 [ 30 128]]

 Prediction Accuracy :  0.6261682242990654
------------------------
Decision Tree
Confusion Matrix : 
[[83 80]
 [83 75]]

 Prediction Accuracy :  0.49221183800623053
------------------------
Random Forest
Confusion Matrix : 
[[105  58]
 [ 52 106]]

 Prediction Accuracy :  0.6573208722741433
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


NN
Confusion Matrix : 
[[99 64]
 [72 86]]

 Prediction Accuracy :  0.5763239875389408
------------------------
liwc_hotels
---
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[90 73]
 [80 78]]

 Prediction Accuracy :  0.5233644859813084
------------------------
SVM
Confusion Matrix : 
[[ 74  89]
 [ 36 122]]

 Prediction Accuracy :  0.6105919003115264
------------------------
Decision Tree
Confusion Matrix : 
[[88 75]
 [79 79]]

 Prediction Accuracy :  0.5202492211838006
------------------------
Random Forest
Confusion Matrix : 
[[102  61]
 [ 50 108]]

 Prediction Accuracy :  0.6542056074766355
------------------------
NN
Confusion Matrix : 
[[  0 163]
 [  0 158]]

 Prediction Accuracy :  0.49221183800623053
------------------------
galc_hotels
---
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[ 57 106]
 [ 47 111]]

 Prediction Accuracy :  0.52336

/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [166]:
comb_hotels_2 = combinations(hotels_features, 2) 
for i,t in enumerate(comb_hotels_2):
    print(t)
    cols_to_use = hotels_features[t[1]].columns.difference(hotels_features[t[0]].columns)
    features = hotels_features[t[0]].join(hotels_features[t[1]][cols_to_use])
    extract_classify_test(features,hotels_classes)
    
comb_hotels_3 = combinations(hotels_features, 3) 
for i,t in enumerate(comb_hotels_3):
    print(t)
    cols_to_use = hotels_features[t[1]].columns.difference(hotels_features[t[0]].columns)
    features = hotels_features[t[0]].join(hotels_features[t[1]][cols_to_use])
    cols_to_use = hotels_features[t[2]].columns.difference(features.columns)
    features = features.join(hotels_features[t[2]][cols_to_use])
    extract_classify_test(features,hotels_classes)
    
comb_hotels_4 = combinations(hotels_features, 4) 
for i,t in enumerate(comb_hotels_4):
    print(t)
    cols_to_use = hotels_features[t[1]].columns.difference(hotels_features[t[0]].columns)
    features = hotels_features[t[0]].join(hotels_features[t[1]][cols_to_use])
    cols_to_use = hotels_features[t[2]].columns.difference(features.columns)
    features = features.join(hotels_features[t[2]][cols_to_use])
    cols_to_use = hotels_features[t[3]].columns.difference(features.columns)
    features = features.join(hotels_features[t[3]][cols_to_use])
    extract_classify_test(features,hotels_classes)
    
comb_hotels_5 = combinations(hotels_features, 5) 
for i,t in enumerate(comb_hotels_5):
    print(t)
    cols_to_use = hotels_features[t[1]].columns.difference(hotels_features[t[0]].columns)
    features = hotels_features[t[0]].join(hotels_features[t[1]][cols_to_use])
    cols_to_use = hotels_features[t[2]].columns.difference(features.columns)
    features = features.join(hotels_features[t[2]][cols_to_use])
    cols_to_use = hotels_features[t[3]].columns.difference(features.columns)
    features = features.join(hotels_features[t[3]][cols_to_use])
    cols_to_use = hotels_features[t[4]].columns.difference(features.columns)
    features = features.join(hotels_features[t[4]][cols_to_use])
    extract_classify_test(features,hotels_classes)

('tf-idf', 'struct_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[131  32]
 [100  58]]

 Prediction Accuracy :  0.5887850467289719
------------------------
SVM
Confusion Matrix : 
[[ 99  64]
 [ 58 100]]

 Prediction Accuracy :  0.6199376947040498
------------------------
Decision Tree
Confusion Matrix : 
[[100  63]
 [ 60  98]]

 Prediction Accuracy :  0.616822429906542
------------------------
Random Forest
Confusion Matrix : 
[[111  52]
 [ 52 106]]

 Prediction Accuracy :  0.67601246105919
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


NN
Confusion Matrix : 
[[105  58]
 [ 67  91]]

 Prediction Accuracy :  0.6105919003115264
------------------------
('tf-idf', 'inq_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[113  50]
 [ 82  76]]

 Prediction Accuracy :  0.5887850467289719
------------------------
SVM
Confusion Matrix : 
[[97 66]
 [63 95]]

 Prediction Accuracy :  0.5981308411214953
------------------------
Decision Tree
Confusion Matrix : 
[[108  55]
 [ 78  80]]

 Prediction Accuracy :  0.5856697819314641
------------------------
Random Forest
Confusion Matrix : 
[[ 98  65]
 [ 52 106]]

 Prediction Accuracy :  0.6355140186915887
------------------------
NN
Confusion Matrix : 
[[  0 163]
 [  0 158]]

 Prediction Accuracy :  0.49221183800623053
------------------------
('tf-idf', 'liwc_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[145  18]
 [113  45]]

 Pre

/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


NN
Confusion Matrix : 
[[94 69]
 [85 73]]

 Prediction Accuracy :  0.5202492211838006
------------------------
('tf-idf', 'galc_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[112  51]
 [ 85  73]]

 Prediction Accuracy :  0.5763239875389408
------------------------
SVM
Confusion Matrix : 
[[98 65]
 [59 99]]

 Prediction Accuracy :  0.6137071651090342
------------------------
Decision Tree
Confusion Matrix : 
[[98 65]
 [73 85]]

 Prediction Accuracy :  0.5700934579439252
------------------------
Random Forest
Confusion Matrix : 
[[ 96  67]
 [ 57 101]]

 Prediction Accuracy :  0.6137071651090342
------------------------
NN
Confusion Matrix : 
[[92 71]
 [63 95]]

 Prediction Accuracy :  0.5825545171339563
------------------------
('struct_hotels', 'inq_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[92 71]
 [71 87]]

 Prediction Ac

/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


NN
Confusion Matrix : 
[[90 73]
 [67 91]]

 Prediction Accuracy :  0.5638629283489096
------------------------
('struct_hotels', 'galc_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[135  28]
 [111  47]]

 Prediction Accuracy :  0.5669781931464174
------------------------
SVM
Confusion Matrix : 
[[ 83  80]
 [ 35 123]]

 Prediction Accuracy :  0.6417445482866043
------------------------
Decision Tree
Confusion Matrix : 
[[102  61]
 [ 78  80]]

 Prediction Accuracy :  0.5669781931464174
------------------------
Random Forest
Confusion Matrix : 
[[112  51]
 [ 49 109]]

 Prediction Accuracy :  0.6884735202492211
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


NN
Confusion Matrix : 
[[100  63]
 [ 58 100]]

 Prediction Accuracy :  0.6230529595015576
------------------------
('inq_hotels', 'liwc_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[104  59]
 [ 78  80]]

 Prediction Accuracy :  0.573208722741433
------------------------
SVM
Confusion Matrix : 
[[100  63]
 [ 42 116]]

 Prediction Accuracy :  0.6728971962616822
------------------------
Decision Tree
Confusion Matrix : 
[[92 71]
 [66 92]]

 Prediction Accuracy :  0.573208722741433
------------------------
Random Forest
Confusion Matrix : 
[[114  49]
 [ 52 106]]

 Prediction Accuracy :  0.6853582554517134
------------------------
NN
Confusion Matrix : 
[[125  38]
 [ 69  89]]

 Prediction Accuracy :  0.6666666666666666
------------------------
('inq_hotels', 'galc_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[88 75]
 [70 88]]

 P

/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


NN
Confusion Matrix : 
[[98 65]
 [59 99]]

 Prediction Accuracy :  0.6137071651090342
------------------------
('liwc_hotels', 'galc_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[117  46]
 [ 90  68]]

 Prediction Accuracy :  0.5763239875389408
------------------------
SVM
Confusion Matrix : 
[[ 77  86]
 [ 36 122]]

 Prediction Accuracy :  0.6199376947040498
------------------------
Decision Tree
Confusion Matrix : 
[[86 77]
 [73 85]]

 Prediction Accuracy :  0.5327102803738317
------------------------
Random Forest
Confusion Matrix : 
[[ 98  65]
 [ 47 111]]

 Prediction Accuracy :  0.6510903426791277
------------------------
NN
Confusion Matrix : 
[[162   1]
 [156   2]]

 Prediction Accuracy :  0.5109034267912772
------------------------
('tf-idf', 'struct_hotels', 'inq_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[131  32]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


NN
Confusion Matrix : 
[[105  58]
 [ 67  91]]

 Prediction Accuracy :  0.6105919003115264
------------------------
('tf-idf', 'struct_hotels', 'liwc_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[146  17]
 [117  41]]

 Prediction Accuracy :  0.5825545171339563
------------------------
SVM
Confusion Matrix : 
[[90 73]
 [60 98]]

 Prediction Accuracy :  0.5856697819314641
------------------------
Decision Tree
Confusion Matrix : 
[[107  56]
 [ 68  90]]

 Prediction Accuracy :  0.6137071651090342
------------------------
Random Forest
Confusion Matrix : 
[[110  53]
 [ 49 109]]

 Prediction Accuracy :  0.6822429906542056
------------------------
NN
Confusion Matrix : 
[[  0 163]
 [  0 158]]

 Prediction Accuracy :  0.49221183800623053
------------------------
('tf-idf', 'struct_hotels', 'galc_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Mat

/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


NN
Confusion Matrix : 
[[94 69]
 [85 73]]

 Prediction Accuracy :  0.5202492211838006
------------------------
('tf-idf', 'inq_hotels', 'galc_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[112  51]
 [ 85  73]]

 Prediction Accuracy :  0.5763239875389408
------------------------
SVM
Confusion Matrix : 
[[98 65]
 [59 99]]

 Prediction Accuracy :  0.6137071651090342
------------------------
Decision Tree
Confusion Matrix : 
[[96 67]
 [68 90]]

 Prediction Accuracy :  0.5794392523364486
------------------------
Random Forest
Confusion Matrix : 
[[ 96  67]
 [ 57 101]]

 Prediction Accuracy :  0.6137071651090342
------------------------
NN
Confusion Matrix : 
[[92 71]
 [63 95]]

 Prediction Accuracy :  0.5825545171339563
------------------------
('tf-idf', 'liwc_hotels', 'galc_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[144  19]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


NN
Confusion Matrix : 
[[92 71]
 [59 99]]

 Prediction Accuracy :  0.5950155763239875
------------------------
('struct_hotels', 'inq_hotels', 'liwc_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[104  59]
 [ 79  79]]

 Prediction Accuracy :  0.5700934579439252
------------------------
SVM
Confusion Matrix : 
[[100  63]
 [ 45 113]]

 Prediction Accuracy :  0.6635514018691588
------------------------
Decision Tree
Confusion Matrix : 
[[97 66]
 [68 90]]

 Prediction Accuracy :  0.5825545171339563
------------------------
Random Forest
Confusion Matrix : 
[[122  41]
 [ 53 105]]

 Prediction Accuracy :  0.7071651090342679
------------------------
NN
Confusion Matrix : 
[[  0 163]
 [  0 158]]

 Prediction Accuracy :  0.49221183800623053
------------------------
('struct_hotels', 'inq_hotels', 'galc_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion

/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


NN
Confusion Matrix : 
[[91 72]
 [66 92]]

 Prediction Accuracy :  0.5700934579439252
------------------------
('inq_hotels', 'liwc_hotels', 'galc_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[109  54]
 [ 77  81]]

 Prediction Accuracy :  0.5919003115264797
------------------------
SVM
Confusion Matrix : 
[[101  62]
 [ 41 117]]

 Prediction Accuracy :  0.6791277258566978
------------------------
Decision Tree
Confusion Matrix : 
[[93 70]
 [69 89]]

 Prediction Accuracy :  0.5669781931464174
------------------------
Random Forest
Confusion Matrix : 
[[115  48]
 [ 46 112]]

 Prediction Accuracy :  0.7071651090342679
------------------------
NN
Confusion Matrix : 
[[104  59]
 [ 61  97]]

 Prediction Accuracy :  0.6261682242990654
------------------------
('tf-idf', 'struct_hotels', 'inq_hotels', 'liwc_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Co

/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


NN
Confusion Matrix : 
[[98 65]
 [73 85]]

 Prediction Accuracy :  0.5700934579439252
------------------------
('tf-idf', 'inq_hotels', 'liwc_hotels', 'galc_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[144  19]
 [115  43]]

 Prediction Accuracy :  0.5825545171339563
------------------------
SVM
Confusion Matrix : 
[[89 74]
 [65 93]]

 Prediction Accuracy :  0.5669781931464174
------------------------
Decision Tree
Confusion Matrix : 
[[91 72]
 [59 99]]

 Prediction Accuracy :  0.5919003115264797
------------------------
Random Forest
Confusion Matrix : 
[[ 95  68]
 [ 44 114]]

 Prediction Accuracy :  0.6510903426791277
------------------------


/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


NN
Confusion Matrix : 
[[92 71]
 [59 99]]

 Prediction Accuracy :  0.5950155763239875
------------------------
('struct_hotels', 'inq_hotels', 'liwc_hotels', 'galc_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to integers : [0 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[108  55]
 [ 78  80]]

 Prediction Accuracy :  0.5856697819314641
------------------------
SVM
Confusion Matrix : 
[[103  60]
 [ 42 116]]

 Prediction Accuracy :  0.6822429906542056
------------------------
Decision Tree
Confusion Matrix : 
[[98 65]
 [61 97]]

 Prediction Accuracy :  0.6074766355140186
------------------------
Random Forest
Confusion Matrix : 
[[122  41]
 [ 54 104]]

 Prediction Accuracy :  0.7040498442367601
------------------------
NN
Confusion Matrix : 
[[109  54]
 [ 63  95]]

 Prediction Accuracy :  0.6355140186915887
------------------------
('tf-idf', 'struct_hotels', 'inq_hotels', 'liwc_hotels', 'galc_hotels')
Classes found :  ['helpful' 'not_helpful']

Classes converted to in

/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


# Helping methods (run first)

In [59]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer 
import re
from collections import Counter
import liwc
import math
import json
import os


def extract_classify_test(features,classes):
    
    ####### Build the model 
    
    #Create Labels and integer classes
    from sklearn import preprocessing

    le = preprocessing.LabelEncoder()
    le.fit(classes)
    print("Classes found : ", le.classes_)

    #Convert classes to integers for use with ML
    int_classes = le.transform(classes)
    print("\nClasses converted to integers :", int_classes)

    from sklearn.model_selection import train_test_split

    #Split as training and testing sets
    xtrain, xtest, ytrain, ytest = train_test_split(features, int_classes,random_state=1)
    
    
    ####### Classify & Test
    
    from sklearn.naive_bayes import MultinomialNB
    classifier_1 = MultinomialNB().fit(xtrain, ytrain)
    print("NB")
    test(classifier_1,xtest,ytest)

    from sklearn import svm
    classifier_2 = svm.SVC(kernel='linear').fit(xtrain, ytrain)
    print("SVM")
    test(classifier_2,xtest,ytest)

    from sklearn import tree
    clf_3 = tree.DecisionTreeClassifier().fit(xtrain, ytrain)
    print("Decision Tree")
    test(clf_3,xtest,ytest)

    from sklearn.ensemble import RandomForestClassifier

    clf_4 = RandomForestClassifier(max_depth=2, random_state=0).fit(xtrain,ytrain)
    print("Random Forest")
    test(clf_4,xtest,ytest)

    from sklearn.neural_network import MLPClassifier
    clf_5 = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(20, 2), random_state=0).fit(xtrain,ytrain)
    print("NN")
    test(clf_5,xtest,ytest)
    
def replace(x):
    if x != "helpful":
        return "not_helpful"
    else:
        return "helpful"

def test(clf,xtest,ytest):
    from sklearn import metrics
    #Predict on test data
    predictions=clf.predict(xtest)
    print("Confusion Matrix : ")
    print(metrics.confusion_matrix(ytest, predictions))
    print("\n Prediction Accuracy : ",  \
          metrics.accuracy_score(ytest, predictions) )
    print("------------------------")
    
####### Features methods 


def extract_tfidf(reviews):
        
    import nltk
    nltk.download('stopwords')
    from nltk.corpus import stopwords

    #setup wordnet for lemmatization
    nltk.download('wordnet')
    from nltk.stem import WordNetLemmatizer
    lemmatizer = WordNetLemmatizer()

    from sklearn.feature_extraction.text import TfidfVectorizer

    #Custom tokenizer that will perform tokenization, stopword removal
    #and lemmatization
    def customtokenize(str):
        tokens=nltk.word_tokenize(str)

        #Replace special characters
        token_list2 = [word.replace("'", "") for word in tokens ]

        #Remove punctuations
        token_list3 = list(filter(lambda token: nltk.tokenize.punkt.PunktToken(token).is_non_punct, token_list2))

        #Convert to lower case
        token_list4=[word.lower() for word in token_list3 ]

        #remove stop words
        nostop = list(filter(lambda token: token not in stopwords.words('english'), token_list4))

        #lemmatized
        lemmatized=[lemmatizer.lemmatize(word) for word in nostop ]

        return lemmatized

    #Generate TFIDF matrix
    vectorizer = TfidfVectorizer(tokenizer=customtokenize)
    tfidf = vectorizer.fit_transform(reviews)

    print("\nSample feature names identified : ", vectorizer.get_feature_names()[:25])
    print("\nSize of TFIDF matrix : ",tfidf.shape)

    return tfidf
    
def struct_extract(reviews):

    """
    review list(str): list of sentences 
    """
    
    #initiate dataframe
    results = pd.DataFrame(reviews)
    results.columns = ['review']

    #define local funcs
    def avg_sent_length(string):
        sentences = string.split('.')
        sum_len = 0        
        for i,s in enumerate(sentences):
            sum_len += len(s)
        return sum_len/len(sentences)

    def per_of_q(string):
    
        num_q = string.count("?")
        new_string = string.replace("?",".")
        sentences = new_string.split(".")
        
        return num_q/len(sentences)
    
    #extract feats
    results['length'] = results.review.apply(lambda x: len(x))
    results['num_tokens'] = results.review.apply(lambda x: len(x.split(' ')))
    results['num_sentences'] = results.review.apply(lambda x: x.count('.'))
    results['avg_sent_len'] = results.review.apply(lambda x: avg_sent_length(x))
    results['num_exclm_mark'] = results.review.apply(lambda x: x.count('!'))
    results['ratio_q'] = results.review.apply(lambda x: per_of_q(x))
    
    #drop the review
    results = results.drop(columns=['review'])
    
    #scale
    results = results - results.min()
    results = results / results.max()
    results = results.fillna(0)
    
    #save file
    return results

# GALC

def galc_extract(reviews):
    
    # read galc dictionary
    with open('galc_dict.json') as json_file:
        galc_dict = json.load(json_file)
    
    #init dataframe
    galc_feature = pd.DataFrame(np.zeros((len(reviews),len(galc_dict))))
    galc_feature.columns = list(galc_dict.keys())

    def galc_vector_feature(review):
        ps = PorterStemmer()
        dic = dict.fromkeys(galc_dict.keys(),0)

        for w in review.split(' '):
            word = w.replace('.','')
            stemmed = ps.stem(word)

            for categ,words in galc_dict.items():
                if stemmed in words:
                    dic[categ] += 1

        return dic.values()

    for i,r in galc_feature.iterrows():
        galc_feature.iloc[i] = galc_vector_feature(reviews[i])
        
    
    #scale
    galc_feature = galc_feature - galc_feature.min()
    galc_feature = galc_feature / galc_feature.max()
    galc_feature = galc_feature.fillna(0)

    #Save file
    return galc_feature


# LIWC 

def liwc_extract(reviews):
    import liwc
    parse, category_names = liwc.load_token_parser('LIWC2007_English100131.dic')

    # define helpers
    def tokenize(text):
        # you may want to use a smarter tokenizer
        for match in re.finditer(r'\w+', text, re.UNICODE):
            yield match.group(0)

    def liwc_features(text):
        
        dic = dict.fromkeys(category_names,0)

        gettysburg_tokens = tokenize(text)
        from collections import Counter
        gettysburg_counts = Counter(category for token in gettysburg_tokens for category in parse(token))

        for k,v in gettysburg_counts.items():
            dic[k] = v

        return dic.values()
    
    # init dataframe
    liwc_feature = pd.DataFrame(np.zeros((len(reviews),len(category_names))))
    liwc_feature.columns = category_names
    
    #extract feats
    for i,r in liwc_feature.iterrows():
        liwc_feature.iloc[i] = liwc_features(reviews[i])
    
    #scale
    liwc_feature = liwc_feature - liwc_feature.min()
    liwc_feature = liwc_feature / liwc_feature.max()
    liwc_feature = liwc_feature.fillna(0)

    #save file
    return liwc_feature

# INQURIER 

def inq_extract(reviews):
    
    #read inq
    inq = pd.read_excel('inquirerbasic.xls')
    inq_categs = list(inq.columns)
    
    #init dataframe
    inq_features = np.zeros((1,len(inq_categs)),dtype=int)

    #extract features 
    for review in reviews:
        inq_feat = dict.fromkeys(inq_categs,0)
        for w in review.split(' '):
            clean = w.strip().replace('.',"").replace("?",'').replace(",","").replace(";",'').upper()
            # if the word exists in the dictionary
            if len(inq[inq['Entry'] == clean]) > 0:
                row = inq[inq['Entry']==clean].to_dict()
                for k,v in row.items():
                    vv = list(v.values())[0]
                    if isinstance(vv,str):
                        inq_feat[k] += 1

        # convert the dict to one row features 
        inq_feat_row = np.array(list(inq_feat.values()),dtype=int).reshape((1,len(inq_categs)))

        #combine with big matrix
        inq_features = np.concatenate((inq_features,inq_feat_row),axis=0)
    
    
    #scale
    inq_features = pd.DataFrame(inq_features)
    inq_features = inq_features - inq_features.min()
    inq_features = inq_features / inq_features.max()
    inq_features = inq_features.fillna(0)
    
    # save file
    return inq_features