In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer 
import re
from collections import Counter
import liwc
import math
import json
import os
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
import arabic_reviews

In [3]:
hotels_data = pd.read_csv("Hotel_labeled_all_rows_with_ratings.csv")
hotels_conf = hotels_data[(hotels_data["confidence"] == 1.0) & (hotels_data["helpfulness"] == "helpful") | (hotels_data["helpfulness"] != "helpful")]
classes = hotels_conf["ratings_combined"].map(lambda x: "pos_rating" if x == "pos_rating" else "neg_rating")

In [5]:
hotels_data = pd.read_csv("appen_translated - hotels.csv")
hotels_conf = hotels_data[(hotels_data["confidence"] == 1.0) & (hotels_data["helpfulness"] == "helpful") | (hotels_data["helpfulness"] != "helpful")]

In [6]:
tf_idf_conf = arabic_reviews.extract_tfidf(hotels_conf["review_en"])
struct = arabic_reviews.struct_extract(hotels_conf["review_en"])

[nltk_data] Downloading package stopwords to /Users/Omar/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/Omar/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!



Sample feature names identified :  ['.2', '1', '1.', '10', '100', '11', '12', '13', '2', '2.', '20', '24', '24-hour', '25', '3', '3.', '30', '300', '4', '4-star', '45', '5', '5-star', '500', '6']

Size of TFIDF matrix :  (1624, 1300)


In [9]:
inq = arabic_reviews.inq_extract(hotels_conf["review_en"])

In [11]:
hotels_conf["review_en"]

0       good. Director of Customer Service Miss Bushra...
1       Acceptable. Excellent location. Waiting for a ...
3       "Excellent". Everything wonderful and clean an...
5       disappointing. Location - swimming pool. Recep...
7       "it's OK". Employee Ambassador and Professor K...
                              ...                        
2776    "Rather comfortable." When I entered the frank...
2778    "Excellent". Ok hotel I Bs unhelpful where the...
2779    good. Room was spacious and a large bathroom. ...
2780    very good. - Provides dedicated parking for ho...
2782                      good. . The room is very narrow
Name: review_en, Length: 1624, dtype: object

In [14]:
liwc = arabic_reviews.liwc_extract(hotels_conf["review_en"].values)

In [16]:
galc = arabic_reviews.galc_extract(hotels_conf["review_en"].values)

In [17]:
arabic_reviews.ex_with_best_k(struct,classes,struct.shape[1] if struct.shape[1] < 100 else 100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  50]
 [  0 113]]
Acc:  0.693  Prec:  0.693  Recall:  1.0  F1: 0.819
SVM
Confusion Matrix : 
[[  0  50]
 [  0 113]]
Acc:  0.693  Prec:  0.693  Recall:  1.0  F1: 0.819
Decision Tree
Confusion Matrix : 
[[  8  42]
 [  4 109]]
Acc:  0.718  Prec:  0.722  Recall:  0.965  F1: 0.826
Random Forest
Confusion Matrix : 
[[  0  50]
 [  0 113]]
Acc:  0.693  Prec:  0.693  Recall:  1.0  F1: 0.819
NN
Confusion Matrix : 
[[  0  50]
 [  0 113]]
Acc:  0.693  Prec:  0.693  Recall:  1.0  F1: 0.819
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  50]
 [  0 113]]
Acc:  0.693  Prec:  0.693  Recall:  1.0  F1: 0.819
SVM
Confusion Matrix : 
[[  0  50]
 [  0 113]]
Acc:  0.693  Prec:  0.693  Recall:  1.0  F1: 0.819
Decision Tree
Confusion Matrix : 
[[  7  43]
 [  5 108]]
Acc:  0.70

In [18]:
arabic_reviews.ex_with_best_k(inq[1:],classes,inq.shape[1] if inq.shape[1] < 100 else 100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  50]
 [  0 113]]
Acc:  0.693  Prec:  0.693  Recall:  1.0  F1: 0.819
SVM
Confusion Matrix : 
[[ 21  29]
 [  7 106]]
Acc:  0.779  Prec:  0.785  Recall:  0.938  F1: 0.855
Decision Tree
Confusion Matrix : 
[[ 21  29]
 [  7 106]]
Acc:  0.779  Prec:  0.785  Recall:  0.938  F1: 0.855
Random Forest
Confusion Matrix : 
[[ 21  29]
 [  7 106]]
Acc:  0.779  Prec:  0.785  Recall:  0.938  F1: 0.855
NN
Confusion Matrix : 
[[ 21  29]
 [  7 106]]
Acc:  0.779  Prec:  0.785  Recall:  0.938  F1: 0.855
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  50]
 [  0 113]]
Acc:  0.693  Prec:  0.693  Recall:  1.0  F1: 0.819
SVM
Confusion Matrix : 
[[ 10  40]
 [  1 112]]
Acc:  0.748  Prec:  0.737  Recall:  0.991  F1: 0.845
Decision Tree
Confusion Matrix : 
[[ 22  28]
 [ 12 101]]
Ac

Random Forest
Confusion Matrix : 
[[ 22  28]
 [  5 108]]
Acc:  0.798  Prec:  0.794  Recall:  0.956  F1: 0.867
NN
Confusion Matrix : 
[[ 27  23]
 [ 10 103]]
Acc:  0.798  Prec:  0.817  Recall:  0.912  F1: 0.862
k = ----------  15
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[ 12  38]
 [  1 112]]
Acc:  0.761  Prec:  0.747  Recall:  0.991  F1: 0.852
SVM
Confusion Matrix : 
[[ 23  27]
 [  2 111]]
Acc:  0.822  Prec:  0.804  Recall:  0.982  F1: 0.884
Decision Tree
Confusion Matrix : 
[[ 21  29]
 [ 13 100]]
Acc:  0.742  Prec:  0.775  Recall:  0.885  F1: 0.826
Random Forest
Confusion Matrix : 
[[ 20  30]
 [  3 110]]
Acc:  0.798  Prec:  0.786  Recall:  0.973  F1: 0.87
NN
Confusion Matrix : 
[[ 27  23]
 [ 10 103]]
Acc:  0.798  Prec:  0.817  Recall:  0.912  F1: 0.862
k = ----------  16
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[ 15  35]
 [  1 112]

NN
Confusion Matrix : 
[[ 25  25]
 [ 12 101]]
Acc:  0.773  Prec:  0.802  Recall:  0.894  F1: 0.845
k = ----------  28
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[ 16  34]
 [  1 112]]
Acc:  0.785  Prec:  0.767  Recall:  0.991  F1: 0.865
SVM
Confusion Matrix : 
[[ 23  27]
 [  4 109]]
Acc:  0.81  Prec:  0.801  Recall:  0.965  F1: 0.876
Decision Tree
Confusion Matrix : 
[[18 32]
 [25 88]]
Acc:  0.65  Prec:  0.733  Recall:  0.779  F1: 0.755
Random Forest
Confusion Matrix : 
[[ 18  32]
 [  2 111]]
Acc:  0.791  Prec:  0.776  Recall:  0.982  F1: 0.867
NN
Confusion Matrix : 
[[24 26]
 [14 99]]
Acc:  0.755  Prec:  0.792  Recall:  0.876  F1: 0.832
k = ----------  29
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[ 17  33]
 [  1 112]]
Acc:  0.791  Prec:  0.772  Recall:  0.991  F1: 0.868
SVM
Confusion Matrix : 
[[ 24  26]
 [  4 109]]
Acc:  0.816  Prec

Decision Tree
Confusion Matrix : 
[[25 25]
 [26 87]]
Acc:  0.687  Prec:  0.777  Recall:  0.77  F1: 0.773
Random Forest
Confusion Matrix : 
[[ 20  30]
 [  2 111]]
Acc:  0.804  Prec:  0.787  Recall:  0.982  F1: 0.874
NN
Confusion Matrix : 
[[25 25]
 [17 96]]
Acc:  0.742  Prec:  0.793  Recall:  0.85  F1: 0.821
k = ----------  42
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[ 18  32]
 [  3 110]]
Acc:  0.785  Prec:  0.775  Recall:  0.973  F1: 0.863
SVM
Confusion Matrix : 
[[ 23  27]
 [  5 108]]
Acc:  0.804  Prec:  0.8  Recall:  0.956  F1: 0.871
Decision Tree
Confusion Matrix : 
[[26 24]
 [25 88]]
Acc:  0.699  Prec:  0.786  Recall:  0.779  F1: 0.782
Random Forest
Confusion Matrix : 
[[ 18  32]
 [  3 110]]
Acc:  0.785  Prec:  0.775  Recall:  0.973  F1: 0.863
NN
Confusion Matrix : 
[[29 21]
 [16 97]]
Acc:  0.773  Prec:  0.822  Recall:  0.858  F1: 0.84
k = ----------  43
Classes found :  ['neg_rating' 'pos_rating']

Clas

Random Forest
Confusion Matrix : 
[[ 10  40]
 [  1 112]]
Acc:  0.748  Prec:  0.737  Recall:  0.991  F1: 0.845
NN
Confusion Matrix : 
[[31 19]
 [15 98]]
Acc:  0.791  Prec:  0.838  Recall:  0.867  F1: 0.852
k = ----------  55
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[ 18  32]
 [  3 110]]
Acc:  0.785  Prec:  0.775  Recall:  0.973  F1: 0.863
SVM
Confusion Matrix : 
[[ 23  27]
 [  6 107]]
Acc:  0.798  Prec:  0.799  Recall:  0.947  F1: 0.866
Decision Tree
Confusion Matrix : 
[[27 23]
 [22 91]]
Acc:  0.724  Prec:  0.798  Recall:  0.805  F1: 0.802
Random Forest
Confusion Matrix : 
[[ 15  35]
 [  1 112]]
Acc:  0.779  Prec:  0.762  Recall:  0.991  F1: 0.862
NN
Confusion Matrix : 
[[32 18]
 [19 94]]
Acc:  0.773  Prec:  0.839  Recall:  0.832  F1: 0.836
k = ----------  56
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[ 18  32]
 [  4 109]]
Acc:  0.7

NN
Confusion Matrix : 
[[31 19]
 [16 97]]
Acc:  0.785  Prec:  0.836  Recall:  0.858  F1: 0.847
k = ----------  68
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[ 18  32]
 [  5 108]]
Acc:  0.773  Prec:  0.771  Recall:  0.956  F1: 0.854
SVM
Confusion Matrix : 
[[ 25  25]
 [  7 106]]
Acc:  0.804  Prec:  0.809  Recall:  0.938  F1: 0.869
Decision Tree
Confusion Matrix : 
[[26 24]
 [26 87]]
Acc:  0.693  Prec:  0.784  Recall:  0.77  F1: 0.777
Random Forest
Confusion Matrix : 
[[  6  44]
 [  0 113]]
Acc:  0.73  Prec:  0.72  Recall:  1.0  F1: 0.837
NN
Confusion Matrix : 
[[31 19]
 [14 99]]
Acc:  0.798  Prec:  0.839  Recall:  0.876  F1: 0.857
k = ----------  69
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[ 18  32]
 [  5 108]]
Acc:  0.773  Prec:  0.771  Recall:  0.956  F1: 0.854
SVM
Confusion Matrix : 
[[ 25  25]
 [  7 106]]
Acc:  0.804  Prec:  0.80

SVM
Confusion Matrix : 
[[ 25  25]
 [  7 106]]
Acc:  0.804  Prec:  0.809  Recall:  0.938  F1: 0.869
Decision Tree
Confusion Matrix : 
[[18 32]
 [25 88]]
Acc:  0.65  Prec:  0.733  Recall:  0.779  F1: 0.755
Random Forest
Confusion Matrix : 
[[  7  43]
 [  0 113]]
Acc:  0.736  Prec:  0.724  Recall:  1.0  F1: 0.84
NN
Confusion Matrix : 
[[30 20]
 [17 96]]
Acc:  0.773  Prec:  0.828  Recall:  0.85  F1: 0.838
k = ----------  82
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[ 19  31]
 [  5 108]]
Acc:  0.779  Prec:  0.777  Recall:  0.956  F1: 0.857
SVM
Confusion Matrix : 
[[ 25  25]
 [  7 106]]
Acc:  0.804  Prec:  0.809  Recall:  0.938  F1: 0.869
Decision Tree
Confusion Matrix : 
[[25 25]
 [25 88]]
Acc:  0.693  Prec:  0.779  Recall:  0.779  F1: 0.779
Random Forest
Confusion Matrix : 
[[  9  41]
 [  0 113]]
Acc:  0.748  Prec:  0.734  Recall:  1.0  F1: 0.846
NN
Confusion Matrix : 
[[28 22]
 [17 96]]
Acc:  0.761  Prec:  0.81

Random Forest
Confusion Matrix : 
[[  2  48]
 [  0 113]]
Acc:  0.706  Prec:  0.702  Recall:  1.0  F1: 0.825
NN
Confusion Matrix : 
[[30 20]
 [15 98]]
Acc:  0.785  Prec:  0.831  Recall:  0.867  F1: 0.848
k = ----------  95
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[ 19  31]
 [  5 108]]
Acc:  0.779  Prec:  0.777  Recall:  0.956  F1: 0.857
SVM
Confusion Matrix : 
[[ 25  25]
 [  7 106]]
Acc:  0.804  Prec:  0.809  Recall:  0.938  F1: 0.869
Decision Tree
Confusion Matrix : 
[[21 29]
 [24 89]]
Acc:  0.675  Prec:  0.754  Recall:  0.788  F1: 0.771
Random Forest
Confusion Matrix : 
[[  3  47]
 [  0 113]]
Acc:  0.712  Prec:  0.706  Recall:  1.0  F1: 0.828
NN
Confusion Matrix : 
[[30 20]
 [17 96]]
Acc:  0.773  Prec:  0.828  Recall:  0.85  F1: 0.838
k = ----------  96
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[ 19  31]
 [  5 108]]
Acc:  0.779  P

In [19]:
arabic_reviews.ex_with_best_k(galc,classes,galc.shape[1] if galc.shape[1] < 100 else 100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  50]
 [  0 113]]
Acc:  0.693  Prec:  0.693  Recall:  1.0  F1: 0.819
SVM
Confusion Matrix : 
[[  6  44]
 [  0 113]]
Acc:  0.73  Prec:  0.72  Recall:  1.0  F1: 0.837
Decision Tree
Confusion Matrix : 
[[  6  44]
 [  0 113]]
Acc:  0.73  Prec:  0.72  Recall:  1.0  F1: 0.837
Random Forest
Confusion Matrix : 
[[  6  44]
 [  0 113]]
Acc:  0.73  Prec:  0.72  Recall:  1.0  F1: 0.837
NN
Confusion Matrix : 
[[  6  44]
 [  0 113]]
Acc:  0.73  Prec:  0.72  Recall:  1.0  F1: 0.837
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[  6  44]
 [  0 113]]
Acc:  0.73  Prec:  0.72  Recall:  1.0  F1: 0.837
SVM
Confusion Matrix : 
[[ 22  28]
 [  7 106]]
Acc:  0.785  Prec:  0.791  Recall:  0.938  F1: 0.858
Decision Tree
Confusion Matrix : 
[[ 22  28]
 [  7 106]]
Acc:  0.785  Prec:  

Random Forest
Confusion Matrix : 
[[  6  44]
 [  0 113]]
Acc:  0.73  Prec:  0.72  Recall:  1.0  F1: 0.837
NN
Confusion Matrix : 
[[ 19  31]
 [  5 108]]
Acc:  0.779  Prec:  0.777  Recall:  0.956  F1: 0.857
k = ----------  15
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[ 10  40]
 [  0 113]]
Acc:  0.755  Prec:  0.739  Recall:  1.0  F1: 0.85
SVM
Confusion Matrix : 
[[ 13  37]
 [  2 111]]
Acc:  0.761  Prec:  0.75  Recall:  0.982  F1: 0.851
Decision Tree
Confusion Matrix : 
[[ 19  31]
 [  5 108]]
Acc:  0.779  Prec:  0.777  Recall:  0.956  F1: 0.857
Random Forest
Confusion Matrix : 
[[ 12  38]
 [  5 108]]
Acc:  0.736  Prec:  0.74  Recall:  0.956  F1: 0.834
NN
Confusion Matrix : 
[[ 19  31]
 [  5 108]]
Acc:  0.779  Prec:  0.777  Recall:  0.956  F1: 0.857
k = ----------  16
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[ 10  40]
 [  0 113]]
Acc:  

NN
Confusion Matrix : 
[[ 20  30]
 [  5 108]]
Acc:  0.785  Prec:  0.783  Recall:  0.956  F1: 0.861
k = ----------  28
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[ 10  40]
 [  0 113]]
Acc:  0.755  Prec:  0.739  Recall:  1.0  F1: 0.85
SVM
Confusion Matrix : 
[[ 19  31]
 [  5 108]]
Acc:  0.779  Prec:  0.777  Recall:  0.956  F1: 0.857
Decision Tree
Confusion Matrix : 
[[ 19  31]
 [  5 108]]
Acc:  0.779  Prec:  0.777  Recall:  0.956  F1: 0.857
Random Forest
Confusion Matrix : 
[[  3  47]
 [  0 113]]
Acc:  0.712  Prec:  0.706  Recall:  1.0  F1: 0.828
NN
Confusion Matrix : 
[[ 21  29]
 [  6 107]]
Acc:  0.785  Prec:  0.787  Recall:  0.947  F1: 0.859
k = ----------  29
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[ 10  40]
 [  0 113]]
Acc:  0.755  Prec:  0.739  Recall:  1.0  F1: 0.85
SVM
Confusion Matrix : 
[[ 19  31]
 [  5 108]]
Acc:  0.779  Pr

In [20]:
arabic_reviews.ex_with_best_k(liwc,classes,liwc.shape[1] if liwc.shape[1] < 100 else 100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  50]
 [  0 113]]
Acc:  0.693  Prec:  0.693  Recall:  1.0  F1: 0.819
SVM
Confusion Matrix : 
[[ 18  32]
 [  5 108]]
Acc:  0.773  Prec:  0.771  Recall:  0.956  F1: 0.854
Decision Tree
Confusion Matrix : 
[[ 18  32]
 [  5 108]]
Acc:  0.773  Prec:  0.771  Recall:  0.956  F1: 0.854
Random Forest
Confusion Matrix : 
[[ 18  32]
 [  5 108]]
Acc:  0.773  Prec:  0.771  Recall:  0.956  F1: 0.854
NN
Confusion Matrix : 
[[ 18  32]
 [  5 108]]
Acc:  0.773  Prec:  0.771  Recall:  0.956  F1: 0.854
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  50]
 [  0 113]]
Acc:  0.693  Prec:  0.693  Recall:  1.0  F1: 0.819
SVM
Confusion Matrix : 
[[ 13  37]
 [  4 109]]
Acc:  0.748  Prec:  0.747  Recall:  0.965  F1: 0.842
Decision Tree
Confusion Matrix : 
[[ 20  30]
 [  6 107]]
Ac

Random Forest
Confusion Matrix : 
[[ 11  39]
 [  3 110]]
Acc:  0.742  Prec:  0.738  Recall:  0.973  F1: 0.84
NN
Confusion Matrix : 
[[ 29  21]
 [ 11 102]]
Acc:  0.804  Prec:  0.829  Recall:  0.903  F1: 0.864
k = ----------  15
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[  1  49]
 [  2 111]]
Acc:  0.687  Prec:  0.694  Recall:  0.982  F1: 0.813
SVM
Confusion Matrix : 
[[ 21  29]
 [  5 108]]
Acc:  0.791  Prec:  0.788  Recall:  0.956  F1: 0.864
Decision Tree
Confusion Matrix : 
[[26 24]
 [17 96]]
Acc:  0.748  Prec:  0.8  Recall:  0.85  F1: 0.824
Random Forest
Confusion Matrix : 
[[ 10  40]
 [  2 111]]
Acc:  0.742  Prec:  0.735  Recall:  0.982  F1: 0.841
NN
Confusion Matrix : 
[[ 32  18]
 [ 10 103]]
Acc:  0.828  Prec:  0.851  Recall:  0.912  F1: 0.88
k = ----------  16
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[  1  49]
 [  2 111]]
Acc:  

NN
Confusion Matrix : 
[[33 17]
 [16 97]]
Acc:  0.798  Prec:  0.851  Recall:  0.858  F1: 0.855
k = ----------  28
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[  1  49]
 [  1 112]]
Acc:  0.693  Prec:  0.696  Recall:  0.991  F1: 0.818
SVM
Confusion Matrix : 
[[ 24  26]
 [  5 108]]
Acc:  0.81  Prec:  0.806  Recall:  0.956  F1: 0.874
Decision Tree
Confusion Matrix : 
[[31 19]
 [23 90]]
Acc:  0.742  Prec:  0.826  Recall:  0.796  F1: 0.811
Random Forest
Confusion Matrix : 
[[  9  41]
 [  1 112]]
Acc:  0.742  Prec:  0.732  Recall:  0.991  F1: 0.842
NN
Confusion Matrix : 
[[29 21]
 [17 96]]
Acc:  0.767  Prec:  0.821  Recall:  0.85  F1: 0.835
k = ----------  29
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[  1  49]
 [  1 112]]
Acc:  0.693  Prec:  0.696  Recall:  0.991  F1: 0.818
SVM
Confusion Matrix : 
[[ 24  26]
 [  5 108]]
Acc:  0.81  Prec:  0.

Decision Tree
Confusion Matrix : 
[[28 22]
 [24 89]]
Acc:  0.718  Prec:  0.802  Recall:  0.788  F1: 0.795
Random Forest
Confusion Matrix : 
[[  8  42]
 [  1 112]]
Acc:  0.736  Prec:  0.727  Recall:  0.991  F1: 0.839
NN
Confusion Matrix : 
[[29 21]
 [17 96]]
Acc:  0.767  Prec:  0.821  Recall:  0.85  F1: 0.835
k = ----------  42
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[  2  48]
 [  1 112]]
Acc:  0.699  Prec:  0.7  Recall:  0.991  F1: 0.821
SVM
Confusion Matrix : 
[[ 25  25]
 [  3 110]]
Acc:  0.828  Prec:  0.815  Recall:  0.973  F1: 0.887
Decision Tree
Confusion Matrix : 
[[28 22]
 [21 92]]
Acc:  0.736  Prec:  0.807  Recall:  0.814  F1: 0.811
Random Forest
Confusion Matrix : 
[[  2  48]
 [  0 113]]
Acc:  0.706  Prec:  0.702  Recall:  1.0  F1: 0.825
NN
Confusion Matrix : 
[[32 18]
 [17 96]]
Acc:  0.785  Prec:  0.842  Recall:  0.85  F1: 0.846
k = ----------  43
Classes found :  ['neg_rating' 'pos_rating']

Class

Random Forest
Confusion Matrix : 
[[  4  46]
 [  0 113]]
Acc:  0.718  Prec:  0.711  Recall:  1.0  F1: 0.831
NN
Confusion Matrix : 
[[  0  50]
 [  0 113]]
Acc:  0.693  Prec:  0.693  Recall:  1.0  F1: 0.819
k = ----------  55
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[  3  47]
 [  1 112]]
Acc:  0.706  Prec:  0.704  Recall:  0.991  F1: 0.824
SVM
Confusion Matrix : 
[[ 25  25]
 [  3 110]]
Acc:  0.828  Prec:  0.815  Recall:  0.973  F1: 0.887
Decision Tree
Confusion Matrix : 
[[22 28]
 [15 98]]
Acc:  0.736  Prec:  0.778  Recall:  0.867  F1: 0.82
Random Forest
Confusion Matrix : 
[[  2  48]
 [  0 113]]
Acc:  0.706  Prec:  0.702  Recall:  1.0  F1: 0.825
NN
Confusion Matrix : 
[[31 19]
 [16 97]]
Acc:  0.785  Prec:  0.836  Recall:  0.858  F1: 0.847
k = ----------  56
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 1]
NB
Confusion Matrix : 
[[  3  47]
 [  1 112]]
Acc:  0.706 

# Do on all data

In [22]:
len(hotels_data)

2784

In [24]:
tf_idf_all = arabic_reviews.extract_tfidf(hotels_data["review_en"])
struct_all = arabic_reviews.struct_extract(hotels_data["review_en"])
inq_all = arabic_reviews.inq_extract(hotels_data["review_en"])
liwc_all = arabic_reviews.liwc_extract(hotels_data["review_en"].values)
galc_all = arabic_reviews.galc_extract(hotels_data["review_en"].values)

[nltk_data] Downloading package stopwords to /Users/Omar/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/Omar/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!



Sample feature names identified :  ['.2', '.agu', '.onsah', '1', '1.', '10', '100', '11', '12', '13', '15', '150', '18', '2', '2.', '20', '24', '24-hour', '25', '250', '3', '3.', '30', '300', '35']

Size of TFIDF matrix :  (2784, 1752)


In [27]:
hotels_data_rt = pd.read_csv("Hotel_labeled_all_rows_with_ratings.csv")
classes = hotels_data_rt["ratings_combined"].map(lambda x: "pos_rating" if x == "pos_rating" else "neg_rating")

In [41]:
arabic_reviews.ex_with_best_k(tf_idf_all[0],classes,100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  0  89]
 [  0 190]]
Acc:  0.681  Prec:  0.681  Recall:  1.0  F1: 0.81
SVM
Confusion Matrix : 
[[ 14  75]
 [  0 190]]
Acc:  0.731  Prec:  0.717  Recall:  1.0  F1: 0.835
Decision Tree
Confusion Matrix : 
[[ 15  74]
 [  0 190]]
Acc:  0.735  Prec:  0.72  Recall:  1.0  F1: 0.837
Random Forest
Confusion Matrix : 
[[ 15  74]
 [  0 190]]
Acc:  0.735  Prec:  0.72  Recall:  1.0  F1: 0.837
NN
Confusion Matrix : 
[[ 15  74]
 [  0 190]]
Acc:  0.735  Prec:  0.72  Recall:  1.0  F1: 0.837
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  0  89]
 [  0 190]]
Acc:  0.681  Prec:  0.681  Recall:  1.0  F1: 0.81
SVM
Confusion Matrix : 
[[ 23  66]
 [  1 189]]
Acc:  0.76  Prec:  0.741  Recall:  0.995  F1: 0.849
Decision Tree
Confusion Matrix : 
[[ 25  64]
 [  1 189]]
Acc:  0.767  Pre

Random Forest
Confusion Matrix : 
[[ 17  72]
 [  0 190]]
Acc:  0.742  Prec:  0.725  Recall:  1.0  F1: 0.841
NN
Confusion Matrix : 
[[ 50  39]
 [  6 184]]
Acc:  0.839  Prec:  0.825  Recall:  0.968  F1: 0.891
k = ----------  15
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 24  65]
 [  1 189]]
Acc:  0.763  Prec:  0.744  Recall:  0.995  F1: 0.851
SVM
Confusion Matrix : 
[[ 42  47]
 [  4 186]]
Acc:  0.817  Prec:  0.798  Recall:  0.979  F1: 0.879
Decision Tree
Confusion Matrix : 
[[ 49  40]
 [ 19 171]]
Acc:  0.789  Prec:  0.81  Recall:  0.9  F1: 0.853
Random Forest
Confusion Matrix : 
[[ 26  63]
 [  2 188]]
Acc:  0.767  Prec:  0.749  Recall:  0.989  F1: 0.853
NN
Confusion Matrix : 
[[ 51  38]
 [  7 183]]
Acc:  0.839  Prec:  0.828  Recall:  0.963  F1: 0.891
k = ----------  16
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 24  65]
 [  1 189]]
Ac

Random Forest
Confusion Matrix : 
[[ 15  74]
 [  0 190]]
Acc:  0.735  Prec:  0.72  Recall:  1.0  F1: 0.837
NN
Confusion Matrix : 
[[ 55  34]
 [ 10 180]]
Acc:  0.842  Prec:  0.841  Recall:  0.947  F1: 0.891
k = ----------  28
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 27  62]
 [  2 188]]
Acc:  0.771  Prec:  0.752  Recall:  0.989  F1: 0.855
SVM
Confusion Matrix : 
[[ 45  44]
 [  3 187]]
Acc:  0.832  Prec:  0.81  Recall:  0.984  F1: 0.888
Decision Tree
Confusion Matrix : 
[[ 53  36]
 [ 19 171]]
Acc:  0.803  Prec:  0.826  Recall:  0.9  F1: 0.861
Random Forest
Confusion Matrix : 
[[  5  84]
 [  1 189]]
Acc:  0.695  Prec:  0.692  Recall:  0.995  F1: 0.816
NN
Confusion Matrix : 
[[ 54  35]
 [  9 181]]
Acc:  0.842  Prec:  0.838  Recall:  0.953  F1: 0.892
k = ----------  29
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 27  62]
 [  2 188]]
Acc

NN
Confusion Matrix : 
[[ 58  31]
 [ 10 180]]
Acc:  0.853  Prec:  0.853  Recall:  0.947  F1: 0.898
k = ----------  41
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 27  62]
 [  2 188]]
Acc:  0.771  Prec:  0.752  Recall:  0.989  F1: 0.855
SVM
Confusion Matrix : 
[[ 44  45]
 [  1 189]]
Acc:  0.835  Prec:  0.808  Recall:  0.995  F1: 0.892
Decision Tree
Confusion Matrix : 
[[ 60  29]
 [ 17 173]]
Acc:  0.835  Prec:  0.856  Recall:  0.911  F1: 0.883
Random Forest
Confusion Matrix : 
[[ 12  77]
 [  1 189]]
Acc:  0.72  Prec:  0.711  Recall:  0.995  F1: 0.829
NN
Confusion Matrix : 
[[ 56  33]
 [  9 181]]
Acc:  0.849  Prec:  0.846  Recall:  0.953  F1: 0.896
k = ----------  42
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 27  62]
 [  2 188]]
Acc:  0.771  Prec:  0.752  Recall:  0.989  F1: 0.855
SVM
Confusion Matrix : 
[[ 45  44]
 [  1 189]]
Acc:  0.

NN
Confusion Matrix : 
[[ 57  32]
 [ 11 179]]
Acc:  0.846  Prec:  0.848  Recall:  0.942  F1: 0.893
k = ----------  54
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 31  58]
 [  2 188]]
Acc:  0.785  Prec:  0.764  Recall:  0.989  F1: 0.862
SVM
Confusion Matrix : 
[[ 47  42]
 [  1 189]]
Acc:  0.846  Prec:  0.818  Recall:  0.995  F1: 0.898
Decision Tree
Confusion Matrix : 
[[ 62  27]
 [ 19 171]]
Acc:  0.835  Prec:  0.864  Recall:  0.9  F1: 0.881
Random Forest
Confusion Matrix : 
[[  3  86]
 [  1 189]]
Acc:  0.688  Prec:  0.687  Recall:  0.995  F1: 0.813
NN
Confusion Matrix : 
[[ 55  34]
 [  8 182]]
Acc:  0.849  Prec:  0.843  Recall:  0.958  F1: 0.897
k = ----------  55
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 32  57]
 [  2 188]]
Acc:  0.789  Prec:  0.767  Recall:  0.989  F1: 0.864
SVM
Confusion Matrix : 
[[ 47  42]
 [  1 189]]
Acc:  0.8

SVM
Confusion Matrix : 
[[ 47  42]
 [  1 189]]
Acc:  0.846  Prec:  0.818  Recall:  0.995  F1: 0.898
Decision Tree
Confusion Matrix : 
[[ 61  28]
 [ 20 170]]
Acc:  0.828  Prec:  0.859  Recall:  0.895  F1: 0.876
Random Forest
Confusion Matrix : 
[[  2  87]
 [  0 190]]
Acc:  0.688  Prec:  0.686  Recall:  1.0  F1: 0.814
NN
Confusion Matrix : 
[[ 61  28]
 [ 13 177]]
Acc:  0.853  Prec:  0.863  Recall:  0.932  F1: 0.896
k = ----------  68
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 32  57]
 [  2 188]]
Acc:  0.789  Prec:  0.767  Recall:  0.989  F1: 0.864
SVM
Confusion Matrix : 
[[ 47  42]
 [  2 188]]
Acc:  0.842  Prec:  0.817  Recall:  0.989  F1: 0.895
Decision Tree
Confusion Matrix : 
[[ 59  30]
 [ 18 172]]
Acc:  0.828  Prec:  0.851  Recall:  0.905  F1: 0.878
Random Forest
Confusion Matrix : 
[[  2  87]
 [  0 190]]
Acc:  0.688  Prec:  0.686  Recall:  1.0  F1: 0.814
NN
Confusion Matrix : 
[[  0  89]
 [  0 190]]
Acc: 

Random Forest
Confusion Matrix : 
[[  0  89]
 [  0 190]]
Acc:  0.681  Prec:  0.681  Recall:  1.0  F1: 0.81
NN
Confusion Matrix : 
[[ 62  27]
 [ 14 176]]
Acc:  0.853  Prec:  0.867  Recall:  0.926  F1: 0.896
k = ----------  81
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 36  53]
 [  2 188]]
Acc:  0.803  Prec:  0.78  Recall:  0.989  F1: 0.872
SVM
Confusion Matrix : 
[[ 49  40]
 [  3 187]]
Acc:  0.846  Prec:  0.824  Recall:  0.984  F1: 0.897
Decision Tree
Confusion Matrix : 
[[ 61  28]
 [ 20 170]]
Acc:  0.828  Prec:  0.859  Recall:  0.895  F1: 0.876
Random Forest
Confusion Matrix : 
[[  2  87]
 [  0 190]]
Acc:  0.688  Prec:  0.686  Recall:  1.0  F1: 0.814
NN
Confusion Matrix : 
[[ 64  25]
 [ 16 174]]
Acc:  0.853  Prec:  0.874  Recall:  0.916  F1: 0.895
k = ----------  82
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 36  53]
 [  2 188]]
Acc

NN
Confusion Matrix : 
[[ 67  22]
 [ 15 175]]
Acc:  0.867  Prec:  0.888  Recall:  0.921  F1: 0.904
k = ----------  94
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 38  51]
 [  2 188]]
Acc:  0.81  Prec:  0.787  Recall:  0.989  F1: 0.876
SVM
Confusion Matrix : 
[[ 48  41]
 [  3 187]]
Acc:  0.842  Prec:  0.82  Recall:  0.984  F1: 0.895
Decision Tree
Confusion Matrix : 
[[ 62  27]
 [ 15 175]]
Acc:  0.849  Prec:  0.866  Recall:  0.921  F1: 0.893
Random Forest
Confusion Matrix : 
[[  2  87]
 [  0 190]]
Acc:  0.688  Prec:  0.686  Recall:  1.0  F1: 0.814
NN
Confusion Matrix : 
[[ 61  28]
 [ 17 173]]
Acc:  0.839  Prec:  0.861  Recall:  0.911  F1: 0.885
k = ----------  95
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 38  51]
 [  2 188]]
Acc:  0.81  Prec:  0.787  Recall:  0.989  F1: 0.876
SVM
Confusion Matrix : 
[[ 48  41]
 [  3 187]]
Acc:  0.842 

In [29]:
arabic_reviews.ex_with_best_k(struct_all,classes,struct_all.shape[1] if struct_all.shape[1] < 100 else 100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  0  89]
 [  0 190]]
Acc:  0.681  Prec:  0.681  Recall:  1.0  F1: 0.81
SVM
Confusion Matrix : 
[[  0  89]
 [  0 190]]
Acc:  0.681  Prec:  0.681  Recall:  1.0  F1: 0.81
Decision Tree
Confusion Matrix : 
[[  7  82]
 [ 10 180]]
Acc:  0.67  Prec:  0.687  Recall:  0.947  F1: 0.796
Random Forest
Confusion Matrix : 
[[  6  83]
 [  5 185]]
Acc:  0.685  Prec:  0.69  Recall:  0.974  F1: 0.808
NN
Confusion Matrix : 
[[  1  88]
 [  0 190]]
Acc:  0.685  Prec:  0.683  Recall:  1.0  F1: 0.812
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  0  89]
 [  0 190]]
Acc:  0.681  Prec:  0.681  Recall:  1.0  F1: 0.81
SVM
Confusion Matrix : 
[[  0  89]
 [  0 190]]
Acc:  0.681  Prec:  0.681  Recall:  1.0  F1: 0.81
Decision Tree
Confusion Matrix : 
[[ 38  51]
 [ 67 123]]
Acc:  0.577  P

In [32]:
arabic_reviews.ex_with_best_k(inq_all[1:],classes,inq_all.shape[1] if inq_all.shape[1] < 100 else 100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  0  89]
 [  0 190]]
Acc:  0.681  Prec:  0.681  Recall:  1.0  F1: 0.81
SVM
Confusion Matrix : 
[[ 19  70]
 [  7 183]]
Acc:  0.724  Prec:  0.723  Recall:  0.963  F1: 0.826
Decision Tree
Confusion Matrix : 
[[ 19  70]
 [  7 183]]
Acc:  0.724  Prec:  0.723  Recall:  0.963  F1: 0.826
Random Forest
Confusion Matrix : 
[[ 19  70]
 [  7 183]]
Acc:  0.724  Prec:  0.723  Recall:  0.963  F1: 0.826
NN
Confusion Matrix : 
[[ 19  70]
 [  7 183]]
Acc:  0.724  Prec:  0.723  Recall:  0.963  F1: 0.826
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  0  89]
 [  0 190]]
Acc:  0.681  Prec:  0.681  Recall:  1.0  F1: 0.81
SVM
Confusion Matrix : 
[[ 19  70]
 [  7 183]]
Acc:  0.724  Prec:  0.723  Recall:  0.963  F1: 0.826
Decision Tree
Confusion Matrix : 
[[ 19  70]
 [  8 182]]
Acc:

SVM
Confusion Matrix : 
[[ 24  65]
 [  8 182]]
Acc:  0.738  Prec:  0.737  Recall:  0.958  F1: 0.833
Decision Tree
Confusion Matrix : 
[[ 33  56]
 [ 15 175]]
Acc:  0.746  Prec:  0.758  Recall:  0.921  F1: 0.831
Random Forest
Confusion Matrix : 
[[ 24  65]
 [  8 182]]
Acc:  0.738  Prec:  0.737  Recall:  0.958  F1: 0.833
NN
Confusion Matrix : 
[[ 36  53]
 [ 11 179]]
Acc:  0.771  Prec:  0.772  Recall:  0.942  F1: 0.848
k = ----------  15
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 20  69]
 [  4 186]]
Acc:  0.738  Prec:  0.729  Recall:  0.979  F1: 0.836
SVM
Confusion Matrix : 
[[ 24  65]
 [  7 183]]
Acc:  0.742  Prec:  0.738  Recall:  0.963  F1: 0.836
Decision Tree
Confusion Matrix : 
[[ 35  54]
 [ 14 176]]
Acc:  0.756  Prec:  0.765  Recall:  0.926  F1: 0.838
Random Forest
Confusion Matrix : 
[[ 23  66]
 [  6 184]]
Acc:  0.742  Prec:  0.736  Recall:  0.968  F1: 0.836
NN
Confusion Matrix : 
[[ 33  56]
 [ 10 180]]
A

SVM
Confusion Matrix : 
[[ 23  66]
 [  8 182]]
Acc:  0.735  Prec:  0.734  Recall:  0.958  F1: 0.831
Decision Tree
Confusion Matrix : 
[[ 39  50]
 [ 30 160]]
Acc:  0.713  Prec:  0.762  Recall:  0.842  F1: 0.8
Random Forest
Confusion Matrix : 
[[ 20  69]
 [  6 184]]
Acc:  0.731  Prec:  0.727  Recall:  0.968  F1: 0.831
NN
Confusion Matrix : 
[[ 30  59]
 [ 21 169]]
Acc:  0.713  Prec:  0.741  Recall:  0.889  F1: 0.809
k = ----------  28
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 19  70]
 [  4 186]]
Acc:  0.735  Prec:  0.727  Recall:  0.979  F1: 0.834
SVM
Confusion Matrix : 
[[ 23  66]
 [  9 181]]
Acc:  0.731  Prec:  0.733  Recall:  0.953  F1: 0.828
Decision Tree
Confusion Matrix : 
[[ 37  52]
 [ 30 160]]
Acc:  0.706  Prec:  0.755  Recall:  0.842  F1: 0.796
Random Forest
Confusion Matrix : 
[[ 21  68]
 [  6 184]]
Acc:  0.735  Prec:  0.73  Recall:  0.968  F1: 0.833
NN
Confusion Matrix : 
[[ 33  56]
 [ 17 173]]
Acc:

SVM
Confusion Matrix : 
[[ 22  67]
 [  9 181]]
Acc:  0.728  Prec:  0.73  Recall:  0.953  F1: 0.826
Decision Tree
Confusion Matrix : 
[[ 40  49]
 [ 33 157]]
Acc:  0.706  Prec:  0.762  Recall:  0.826  F1: 0.793
Random Forest
Confusion Matrix : 
[[ 20  69]
 [  5 185]]
Acc:  0.735  Prec:  0.728  Recall:  0.974  F1: 0.833
NN
Confusion Matrix : 
[[ 35  54]
 [ 24 166]]
Acc:  0.72  Prec:  0.755  Recall:  0.874  F1: 0.81
k = ----------  41
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 22  67]
 [  5 185]]
Acc:  0.742  Prec:  0.734  Recall:  0.974  F1: 0.837
SVM
Confusion Matrix : 
[[ 22  67]
 [  9 181]]
Acc:  0.728  Prec:  0.73  Recall:  0.953  F1: 0.826
Decision Tree
Confusion Matrix : 
[[ 38  51]
 [ 33 157]]
Acc:  0.699  Prec:  0.755  Recall:  0.826  F1: 0.789
Random Forest
Confusion Matrix : 
[[ 21  68]
 [  5 185]]
Acc:  0.738  Prec:  0.731  Recall:  0.974  F1: 0.835
NN
Confusion Matrix : 
[[ 35  54]
 [ 19 171]]
Acc: 

SVM
Confusion Matrix : 
[[ 26  63]
 [  9 181]]
Acc:  0.742  Prec:  0.742  Recall:  0.953  F1: 0.834
Decision Tree
Confusion Matrix : 
[[ 44  45]
 [ 47 143]]
Acc:  0.67  Prec:  0.761  Recall:  0.753  F1: 0.757
Random Forest
Confusion Matrix : 
[[ 18  71]
 [  4 186]]
Acc:  0.731  Prec:  0.724  Recall:  0.979  F1: 0.832
NN
Confusion Matrix : 
[[ 33  56]
 [ 24 166]]
Acc:  0.713  Prec:  0.748  Recall:  0.874  F1: 0.806
k = ----------  54
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 25  64]
 [  6 184]]
Acc:  0.749  Prec:  0.742  Recall:  0.968  F1: 0.84
SVM
Confusion Matrix : 
[[ 25  64]
 [  9 181]]
Acc:  0.738  Prec:  0.739  Recall:  0.953  F1: 0.832
Decision Tree
Confusion Matrix : 
[[ 42  47]
 [ 40 150]]
Acc:  0.688  Prec:  0.761  Recall:  0.789  F1: 0.775
Random Forest
Confusion Matrix : 
[[ 18  71]
 [  5 185]]
Acc:  0.728  Prec:  0.723  Recall:  0.974  F1: 0.83
NN
Confusion Matrix : 
[[ 38  51]
 [ 23 167]]
Acc:

SVM
Confusion Matrix : 
[[ 24  65]
 [  9 181]]
Acc:  0.735  Prec:  0.736  Recall:  0.953  F1: 0.83
Decision Tree
Confusion Matrix : 
[[ 43  46]
 [ 46 144]]
Acc:  0.67  Prec:  0.758  Recall:  0.758  F1: 0.758
Random Forest
Confusion Matrix : 
[[ 15  74]
 [  5 185]]
Acc:  0.717  Prec:  0.714  Recall:  0.974  F1: 0.824
NN
Confusion Matrix : 
[[ 41  48]
 [ 29 161]]
Acc:  0.724  Prec:  0.77  Recall:  0.847  F1: 0.807
k = ----------  67
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 26  63]
 [  6 184]]
Acc:  0.753  Prec:  0.745  Recall:  0.968  F1: 0.842
SVM
Confusion Matrix : 
[[ 24  65]
 [  9 181]]
Acc:  0.735  Prec:  0.736  Recall:  0.953  F1: 0.83
Decision Tree
Confusion Matrix : 
[[ 44  45]
 [ 46 144]]
Acc:  0.674  Prec:  0.762  Recall:  0.758  F1: 0.76
Random Forest
Confusion Matrix : 
[[ 17  72]
 [  6 184]]
Acc:  0.72  Prec:  0.719  Recall:  0.968  F1: 0.825
NN
Confusion Matrix : 
[[ 30  59]
 [ 35 155]]
Acc:  0

SVM
Confusion Matrix : 
[[ 25  64]
 [  9 181]]
Acc:  0.738  Prec:  0.739  Recall:  0.953  F1: 0.832
Decision Tree
Confusion Matrix : 
[[ 45  44]
 [ 47 143]]
Acc:  0.674  Prec:  0.765  Recall:  0.753  F1: 0.759
Random Forest
Confusion Matrix : 
[[ 13  76]
 [  4 186]]
Acc:  0.713  Prec:  0.71  Recall:  0.979  F1: 0.823
NN
Confusion Matrix : 
[[ 42  47]
 [ 42 148]]
Acc:  0.681  Prec:  0.759  Recall:  0.779  F1: 0.769
k = ----------  80
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 26  63]
 [  6 184]]
Acc:  0.753  Prec:  0.745  Recall:  0.968  F1: 0.842
SVM
Confusion Matrix : 
[[ 24  65]
 [  9 181]]
Acc:  0.735  Prec:  0.736  Recall:  0.953  F1: 0.83
Decision Tree
Confusion Matrix : 
[[ 45  44]
 [ 55 135]]
Acc:  0.645  Prec:  0.754  Recall:  0.711  F1: 0.732
Random Forest
Confusion Matrix : 
[[ 10  79]
 [  2 188]]
Acc:  0.71  Prec:  0.704  Recall:  0.989  F1: 0.823
NN
Confusion Matrix : 
[[ 36  53]
 [ 22 168]]
Acc:

SVM
Confusion Matrix : 
[[ 24  65]
 [ 10 180]]
Acc:  0.731  Prec:  0.735  Recall:  0.947  F1: 0.828
Decision Tree
Confusion Matrix : 
[[ 44  45]
 [ 54 136]]
Acc:  0.645  Prec:  0.751  Recall:  0.716  F1: 0.733
Random Forest
Confusion Matrix : 
[[ 16  73]
 [  5 185]]
Acc:  0.72  Prec:  0.717  Recall:  0.974  F1: 0.826
NN
Confusion Matrix : 
[[ 48  41]
 [ 44 146]]
Acc:  0.695  Prec:  0.781  Recall:  0.768  F1: 0.775
k = ----------  93
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[ 27  62]
 [  7 183]]
Acc:  0.753  Prec:  0.747  Recall:  0.963  F1: 0.841
SVM
Confusion Matrix : 
[[ 24  65]
 [ 10 180]]
Acc:  0.731  Prec:  0.735  Recall:  0.947  F1: 0.828
Decision Tree
Confusion Matrix : 
[[ 43  46]
 [ 51 139]]
Acc:  0.652  Prec:  0.751  Recall:  0.732  F1: 0.741
Random Forest
Confusion Matrix : 
[[ 12  77]
 [  2 188]]
Acc:  0.717  Prec:  0.709  Recall:  0.989  F1: 0.826
NN
Confusion Matrix : 
[[ 41  48]
 [ 29 161]]
Ac

In [33]:
arabic_reviews.ex_with_best_k(liwc_all,classes,liwc_all.shape[1] if liwc_all.shape[1] < 100 else 100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  0  89]
 [  0 190]]
Acc:  0.681  Prec:  0.681  Recall:  1.0  F1: 0.81
SVM
Confusion Matrix : 
[[ 10  79]
 [  5 185]]
Acc:  0.699  Prec:  0.701  Recall:  0.974  F1: 0.815
Decision Tree
Confusion Matrix : 
[[ 37  52]
 [ 32 158]]
Acc:  0.699  Prec:  0.752  Recall:  0.832  F1: 0.79
Random Forest
Confusion Matrix : 
[[ 37  52]
 [ 32 158]]
Acc:  0.699  Prec:  0.752  Recall:  0.832  F1: 0.79
NN
Confusion Matrix : 
[[ 37  52]
 [ 32 158]]
Acc:  0.699  Prec:  0.752  Recall:  0.832  F1: 0.79
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  0  89]
 [  0 190]]
Acc:  0.681  Prec:  0.681  Recall:  1.0  F1: 0.81
SVM
Confusion Matrix : 
[[ 15  74]
 [  7 183]]
Acc:  0.71  Prec:  0.712  Recall:  0.963  F1: 0.819
Decision Tree
Confusion Matrix : 
[[ 15  74]
 [  7 183]]
Acc:  0.

Random Forest
Confusion Matrix : 
[[ 14  75]
 [  6 184]]
Acc:  0.71  Prec:  0.71  Recall:  0.968  F1: 0.82
NN
Confusion Matrix : 
[[ 36  53]
 [ 20 170]]
Acc:  0.738  Prec:  0.762  Recall:  0.895  F1: 0.823
k = ----------  15
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  1  88]
 [  2 188]]
Acc:  0.677  Prec:  0.681  Recall:  0.989  F1: 0.807
SVM
Confusion Matrix : 
[[ 23  66]
 [  7 183]]
Acc:  0.738  Prec:  0.735  Recall:  0.963  F1: 0.834
Decision Tree
Confusion Matrix : 
[[ 34  55]
 [ 35 155]]
Acc:  0.677  Prec:  0.738  Recall:  0.816  F1: 0.775
Random Forest
Confusion Matrix : 
[[ 13  76]
 [  5 185]]
Acc:  0.71  Prec:  0.709  Recall:  0.974  F1: 0.82
NN
Confusion Matrix : 
[[ 34  55]
 [ 19 171]]
Acc:  0.735  Prec:  0.757  Recall:  0.9  F1: 0.822
k = ----------  16
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  1  88]
 [  2 188]]
Acc:

NN
Confusion Matrix : 
[[ 36  53]
 [ 30 160]]
Acc:  0.703  Prec:  0.751  Recall:  0.842  F1: 0.794
k = ----------  28
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  3  86]
 [  2 188]]
Acc:  0.685  Prec:  0.686  Recall:  0.989  F1: 0.81
SVM
Confusion Matrix : 
[[ 23  66]
 [  6 184]]
Acc:  0.742  Prec:  0.736  Recall:  0.968  F1: 0.836
Decision Tree
Confusion Matrix : 
[[ 34  55]
 [ 49 141]]
Acc:  0.627  Prec:  0.719  Recall:  0.742  F1: 0.731
Random Forest
Confusion Matrix : 
[[ 12  77]
 [  2 188]]
Acc:  0.717  Prec:  0.709  Recall:  0.989  F1: 0.826
NN
Confusion Matrix : 
[[ 41  48]
 [ 31 159]]
Acc:  0.717  Prec:  0.768  Recall:  0.837  F1: 0.801
k = ----------  29
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  3  86]
 [  2 188]]
Acc:  0.685  Prec:  0.686  Recall:  0.989  F1: 0.81
SVM
Confusion Matrix : 
[[ 26  63]
 [  6 184]]
Acc:  0.7

NN
Confusion Matrix : 
[[ 40  49]
 [ 38 152]]
Acc:  0.688  Prec:  0.756  Recall:  0.8  F1: 0.777
k = ----------  41
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  4  85]
 [  2 188]]
Acc:  0.688  Prec:  0.689  Recall:  0.989  F1: 0.812
SVM
Confusion Matrix : 
[[ 25  64]
 [  6 184]]
Acc:  0.749  Prec:  0.742  Recall:  0.968  F1: 0.84
Decision Tree
Confusion Matrix : 
[[ 37  52]
 [ 38 152]]
Acc:  0.677  Prec:  0.745  Recall:  0.8  F1: 0.772
Random Forest
Confusion Matrix : 
[[  6  83]
 [  1 189]]
Acc:  0.699  Prec:  0.695  Recall:  0.995  F1: 0.818
NN
Confusion Matrix : 
[[ 42  47]
 [ 36 154]]
Acc:  0.703  Prec:  0.766  Recall:  0.811  F1: 0.788
k = ----------  42
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  3  86]
 [  2 188]]
Acc:  0.685  Prec:  0.686  Recall:  0.989  F1: 0.81
SVM
Confusion Matrix : 
[[ 25  64]
 [  6 184]]
Acc:  0.749  

SVM
Confusion Matrix : 
[[ 25  64]
 [  6 184]]
Acc:  0.749  Prec:  0.742  Recall:  0.968  F1: 0.84
Decision Tree
Confusion Matrix : 
[[ 35  54]
 [ 34 156]]
Acc:  0.685  Prec:  0.743  Recall:  0.821  F1: 0.78
Random Forest
Confusion Matrix : 
[[  8  81]
 [  1 189]]
Acc:  0.706  Prec:  0.7  Recall:  0.995  F1: 0.822
NN
Confusion Matrix : 
[[  0  89]
 [  0 190]]
Acc:  0.681  Prec:  0.681  Recall:  1.0  F1: 0.81
k = ----------  55
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  4  85]
 [  2 188]]
Acc:  0.688  Prec:  0.689  Recall:  0.989  F1: 0.812
SVM
Confusion Matrix : 
[[ 25  64]
 [  6 184]]
Acc:  0.749  Prec:  0.742  Recall:  0.968  F1: 0.84
Decision Tree
Confusion Matrix : 
[[ 39  50]
 [ 36 154]]
Acc:  0.692  Prec:  0.755  Recall:  0.811  F1: 0.782
Random Forest
Confusion Matrix : 
[[  6  83]
 [  1 189]]
Acc:  0.699  Prec:  0.695  Recall:  0.995  F1: 0.818
NN
Confusion Matrix : 
[[ 43  46]
 [ 37 153]]
Acc:  0.7

In [34]:
arabic_reviews.ex_with_best_k(galc_all,classes,galc_all.shape[1] if galc_all.shape[1] < 100 else 100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  0  89]
 [  0 190]]
Acc:  0.681  Prec:  0.681  Recall:  1.0  F1: 0.81
SVM
Confusion Matrix : 
[[  2  87]
 [  0 190]]
Acc:  0.688  Prec:  0.686  Recall:  1.0  F1: 0.814
Decision Tree
Confusion Matrix : 
[[  2  87]
 [  0 190]]
Acc:  0.688  Prec:  0.686  Recall:  1.0  F1: 0.814
Random Forest
Confusion Matrix : 
[[  2  87]
 [  0 190]]
Acc:  0.688  Prec:  0.686  Recall:  1.0  F1: 0.814
NN
Confusion Matrix : 
[[  2  87]
 [  0 190]]
Acc:  0.688  Prec:  0.686  Recall:  1.0  F1: 0.814
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  2  87]
 [  0 190]]
Acc:  0.688  Prec:  0.686  Recall:  1.0  F1: 0.814
SVM
Confusion Matrix : 
[[ 18  71]
 [  5 185]]
Acc:  0.728  Prec:  0.723  Recall:  0.974  F1: 0.83
Decision Tree
Confusion Matrix : 
[[ 18  71]
 [  5 185]]
Acc:  0.728 

SVM
Confusion Matrix : 
[[ 18  71]
 [  5 185]]
Acc:  0.728  Prec:  0.723  Recall:  0.974  F1: 0.83
Decision Tree
Confusion Matrix : 
[[ 16  73]
 [  4 186]]
Acc:  0.724  Prec:  0.718  Recall:  0.979  F1: 0.829
Random Forest
Confusion Matrix : 
[[  2  87]
 [  0 190]]
Acc:  0.688  Prec:  0.686  Recall:  1.0  F1: 0.814
NN
Confusion Matrix : 
[[ 16  73]
 [  4 186]]
Acc:  0.724  Prec:  0.718  Recall:  0.979  F1: 0.829
k = ----------  15
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  5  84]
 [  0 190]]
Acc:  0.699  Prec:  0.693  Recall:  1.0  F1: 0.819
SVM
Confusion Matrix : 
[[ 18  71]
 [  5 185]]
Acc:  0.728  Prec:  0.723  Recall:  0.974  F1: 0.83
Decision Tree
Confusion Matrix : 
[[ 16  73]
 [  4 186]]
Acc:  0.724  Prec:  0.718  Recall:  0.979  F1: 0.829
Random Forest
Confusion Matrix : 
[[ 16  73]
 [  3 187]]
Acc:  0.728  Prec:  0.719  Recall:  0.984  F1: 0.831
NN
Confusion Matrix : 
[[ 16  73]
 [  4 186]]
Acc:  0

Random Forest
Confusion Matrix : 
[[ 15  74]
 [  2 188]]
Acc:  0.728  Prec:  0.718  Recall:  0.989  F1: 0.832
NN
Confusion Matrix : 
[[ 19  70]
 [  7 183]]
Acc:  0.724  Prec:  0.723  Recall:  0.963  F1: 0.826
k = ----------  28
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  5  84]
 [  0 190]]
Acc:  0.699  Prec:  0.693  Recall:  1.0  F1: 0.819
SVM
Confusion Matrix : 
[[ 18  71]
 [  5 185]]
Acc:  0.728  Prec:  0.723  Recall:  0.974  F1: 0.83
Decision Tree
Confusion Matrix : 
[[ 19  70]
 [  7 183]]
Acc:  0.724  Prec:  0.723  Recall:  0.963  F1: 0.826
Random Forest
Confusion Matrix : 
[[  0  89]
 [  0 190]]
Acc:  0.681  Prec:  0.681  Recall:  1.0  F1: 0.81
NN
Confusion Matrix : 
[[ 18  71]
 [  7 183]]
Acc:  0.72  Prec:  0.72  Recall:  0.963  F1: 0.824
k = ----------  29
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 1 ... 1 1 0]
NB
Confusion Matrix : 
[[  5  84]
 [  0 190]]
Acc: 

In [42]:
len(hotels_data)

2784

In [43]:
tf_idf_all[1]

TfidfVectorizer(min_df=3,
                tokenizer=<function extract_tfidf.<locals>.customtokenize at 0x7fac9e4c0b00>)

In [44]:
arabic_reviews.top_words(tf_idf_all[1],tf_idf_all[0],classes,76,"star_ratings_arabic_books_top_words.csv")

[('patient', 73.75364172058343),
 ('acceptable', 66.5172545919203),
 ('bad', 61.0755016454422),
 ('disappointing', 49.37364812325451),
 ('weak', 45.59571200798963),
 ('excellent', 42.7615378166276),
 ('exceptional', 41.18617574137844),
 ('hassan', 24.440615132803707),
 ('everything', 18.595195658754232),
 ('old', 16.584089370258422),
 ('gorgeous', 16.415635404545824),
 ('wonderful', 16.299214001954084),
 ('good', 15.119650856618968),
 ('beautiful', 12.190702755852655),
 ('smell', 11.012113257887997),
 ('dirty', 9.740883738627415),
 ('cockroach', 9.111383147252736),
 ('foul', 8.762241440927161),
 ('worst', 8.74887547212042),
 ('nice', 8.16325804990854),
 ('great', 8.081742367258439),
 ('money', 6.693567945966327),
 ('thank', 6.541021249358202),
 ('star', 6.493281893164257),
 ('smelled', 6.450009850054894),
 ('never', 5.998033821051797),
 ('quiet', 5.8537491637866435),
 ('unfortunately', 5.710262282570521),
 ('junk', 5.4277404225490375),
 ('room', 5.409740282473522),
 ('sophisticated', 5