In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer 
import re
from collections import Counter
import liwc
import math
import json
import os
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
import arabic_reviews

In [4]:
books_data = pd.read_csv("Book_labeled_all_rows_with_ratings.csv")
books_conf = books_data[(books_data["confidence"] == 1.0) & (books_data["helpfulness"] == "helpful") | (books_data["helpfulness"] != "helpful")]
classes = books_conf["ratings_combined"].map(lambda x: "pos_rating" if x == "pos_rating" else "neg_rating")

In [5]:
books_data = pd.read_csv("appen_translated - books.csv")
books_conf = books_data[(books_data["confidence"] == 1.0) & (books_data["helpfulness"] == "helpful") | (books_data["helpfulness"] != "helpful")]

In [7]:
tf_idf_conf = arabic_reviews.extract_tfidf(books_conf["review_en"])

[nltk_data] Downloading package stopwords to /Users/Omar/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/Omar/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!



Sample feature names identified :  ['-_-', '..lkn', '1', '1.', '10', '100', '1919', '2', '2.', '20', '2008', '2010', '2013', '25', '3', '3.', '30', '4', '4.', '400', '48', '5', '5.', '6', '6.']

Size of TFIDF matrix :  (1480, 3594)


In [13]:
struct = arabic_reviews.struct_extract(books_conf["review_en"])

In [30]:
struct.shape[1]

6

In [12]:
inq = arabic_reviews.inq_extract(books_conf["review_en"])

In [25]:
galc = arabic_reviews.galc_extract(books_conf["review_en"].values)

In [26]:
liwc = arabic_reviews.liwc_extract(books_conf["review_en"].values)

In [31]:
arabic_reviews.ex_with_best_k(struct,classes,struct.shape[1] if struct.shape[1] < 100 else 100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
SVM
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
Decision Tree
Confusion Matrix : 
[[12 34]
 [29 73]]
Acc:  0.574  Prec:  0.682  Recall:  0.716  F1: 0.699
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
SVM
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
Decision Tree
Confusion Matrix : 
[[17 29]
 [24 78]]
Acc:  0.642  Prec:

In [33]:
arabic_reviews.ex_with_best_k(galc,classes,galc.shape[1] if galc.shape[1] < 100 else 100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
SVM
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
Decision Tree
Confusion Matrix : 
[[  1  45]
 [  0 102]]
Acc:  0.696  Prec:  0.694  Recall:  1.0  F1: 0.819
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[  1  45]
 [  0 102]]
Acc:  0.696  Prec:  0.694  Recall:  1.0  F1: 0.819
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
SVM
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
Decision Tree
Confusion Matrix : 
[[  2  44]
 [  0 102]]
Acc:  0.703 

Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[  9  37]
 [  2 100]]
Acc:  0.736  Prec:  0.73  Recall:  0.98  F1: 0.837
k = ----------  15
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  1  45]
 [  0 102]]
Acc:  0.696  Prec:  0.694  Recall:  1.0  F1: 0.819
SVM
Confusion Matrix : 
[[  1  45]
 [  0 102]]
Acc:  0.696  Prec:  0.694  Recall:  1.0  F1: 0.819
Decision Tree
Confusion Matrix : 
[[  8  38]
 [  2 100]]
Acc:  0.73  Prec:  0.725  Recall:  0.98  F1: 0.833
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[  7  39]
 [  2 100]]
Acc:  0.723  Prec:  0.719  Recall:  0.98  F1: 0.83
k = ----------  16
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  1  45]
 [  0 102]]
Acc:  0.696

Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[ 7 39]
 [ 8 94]]
Acc:  0.682  Prec:  0.707  Recall:  0.922  F1: 0.8
k = ----------  29
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  1  45]
 [  0 102]]
Acc:  0.696  Prec:  0.694  Recall:  1.0  F1: 0.819
SVM
Confusion Matrix : 
[[  2  44]
 [  0 102]]
Acc:  0.703  Prec:  0.699  Recall:  1.0  F1: 0.823
Decision Tree
Confusion Matrix : 
[[ 9 37]
 [11 91]]
Acc:  0.676  Prec:  0.711  Recall:  0.892  F1: 0.791
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[ 8 38]
 [ 7 95]]
Acc:  0.696  Prec:  0.714  Recall:  0.931  F1: 0.809
k = ----------  30
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  1  45]
 [  0 102]]
Acc:  0.696  Prec: 

In [34]:
arabic_reviews.ex_with_best_k(inq[1:],classes,inq.shape[1] if inq.shape[1] < 100 else 100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
SVM
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
Decision Tree
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
SVM
Confusion Matrix : 
[[ 0 46]
 [ 3 99]]
Acc:  0.669  Prec:  0.683  Recall:  0.971  F1: 0.802
Decision Tree
Confusion Matrix : 
[[ 0 46]
 [ 3 99]]
Acc:  0.669  Prec:

Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[12 34]
 [13 89]]
Acc:  0.682  Prec:  0.724  Recall:  0.873  F1: 0.791
k = ----------  15
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  1 101]]
Acc:  0.682  Prec:  0.687  Recall:  0.99  F1: 0.811
SVM
Confusion Matrix : 
[[  0  46]
 [  2 100]]
Acc:  0.676  Prec:  0.685  Recall:  0.98  F1: 0.806
Decision Tree
Confusion Matrix : 
[[15 31]
 [20 82]]
Acc:  0.655  Prec:  0.726  Recall:  0.804  F1: 0.763
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[13 33]
 [13 89]]
Acc:  0.689  Prec:  0.73  Recall:  0.873  F1: 0.795
k = ----------  16
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  2 100]]
Acc:  0.676  Pre

Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[15 31]
 [26 76]]
Acc:  0.615  Prec:  0.71  Recall:  0.745  F1: 0.727
k = ----------  29
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[ 0 46]
 [ 3 99]]
Acc:  0.669  Prec:  0.683  Recall:  0.971  F1: 0.802
SVM
Confusion Matrix : 
[[  0  46]
 [  2 100]]
Acc:  0.676  Prec:  0.685  Recall:  0.98  F1: 0.806
Decision Tree
Confusion Matrix : 
[[18 28]
 [25 77]]
Acc:  0.642  Prec:  0.733  Recall:  0.755  F1: 0.744
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[14 32]
 [22 80]]
Acc:  0.635  Prec:  0.714  Recall:  0.784  F1: 0.748
k = ----------  30
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[ 0 46]
 [ 3 99]]
Acc:  0.669  Prec:  0.6

Acc:  0.581  Prec:  0.708  Recall:  0.667  F1: 0.687
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[14 32]
 [22 80]]
Acc:  0.635  Prec:  0.714  Recall:  0.784  F1: 0.748
k = ----------  43
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[ 0 46]
 [ 3 99]]
Acc:  0.669  Prec:  0.683  Recall:  0.971  F1: 0.802
SVM
Confusion Matrix : 
[[  0  46]
 [  2 100]]
Acc:  0.676  Prec:  0.685  Recall:  0.98  F1: 0.806
Decision Tree
Confusion Matrix : 
[[19 27]
 [33 69]]
Acc:  0.595  Prec:  0.719  Recall:  0.676  F1: 0.697
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[16 30]
 [21 81]]
Acc:  0.655  Prec:  0.73  Recall:  0.794  F1: 0.761
k = ----------  44
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion

NN
Confusion Matrix : 
[[23 23]
 [24 78]]
Acc:  0.682  Prec:  0.772  Recall:  0.765  F1: 0.768
k = ----------  56
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  2 100]]
Acc:  0.676  Prec:  0.685  Recall:  0.98  F1: 0.806
SVM
Confusion Matrix : 
[[ 1 45]
 [ 4 98]]
Acc:  0.669  Prec:  0.685  Recall:  0.961  F1: 0.8
Decision Tree
Confusion Matrix : 
[[19 27]
 [35 67]]
Acc:  0.581  Prec:  0.713  Recall:  0.657  F1: 0.684
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
k = ----------  57
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  2 100]]
Acc:  0.676  Prec:  0.685  Recall:  0.98  F1: 0.806
SVM
Confusion Matrix : 
[[ 1 45]
 [ 4 98]]
Acc:  0.669  Prec:  0.685  Reca

Confusion Matrix : 
[[  2  44]
 [  2 100]]
Acc:  0.689  Prec:  0.694  Recall:  0.98  F1: 0.813
Decision Tree
Confusion Matrix : 
[[21 25]
 [30 72]]
Acc:  0.628  Prec:  0.742  Recall:  0.706  F1: 0.724
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[19 27]
 [22 80]]
Acc:  0.669  Prec:  0.748  Recall:  0.784  F1: 0.766
k = ----------  70
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[ 0 46]
 [ 3 99]]
Acc:  0.669  Prec:  0.683  Recall:  0.971  F1: 0.802
SVM
Confusion Matrix : 
[[ 2 44]
 [ 3 99]]
Acc:  0.682  Prec:  0.692  Recall:  0.971  F1: 0.808
Decision Tree
Confusion Matrix : 
[[18 28]
 [34 68]]
Acc:  0.581  Prec:  0.708  Recall:  0.667  F1: 0.687
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[18 28]
 [19 83]]
Acc:  0.682  Prec:  0.748  Recall:

Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[20 26]
 [23 79]]
Acc:  0.669  Prec:  0.752  Recall:  0.775  F1: 0.763
k = ----------  83
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[ 0 46]
 [ 3 99]]
Acc:  0.669  Prec:  0.683  Recall:  0.971  F1: 0.802
SVM
Confusion Matrix : 
[[ 2 44]
 [ 3 99]]
Acc:  0.682  Prec:  0.692  Recall:  0.971  F1: 0.808
Decision Tree
Confusion Matrix : 
[[17 29]
 [39 63]]
Acc:  0.541  Prec:  0.685  Recall:  0.618  F1: 0.649
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[15 31]
 [27 75]]
Acc:  0.608  Prec:  0.708  Recall:  0.735  F1: 0.721
k = ----------  84
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[ 0 46]
 [ 3 99]]
Acc:  0.669  Prec:  0.683

Confusion Matrix : 
[[ 2 44]
 [ 3 99]]
Acc:  0.682  Prec:  0.692  Recall:  0.971  F1: 0.808
Decision Tree
Confusion Matrix : 
[[19 27]
 [32 70]]
Acc:  0.601  Prec:  0.722  Recall:  0.686  F1: 0.704
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[15 31]
 [21 81]]
Acc:  0.649  Prec:  0.723  Recall:  0.794  F1: 0.757
k = ----------  97
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[ 0 46]
 [ 3 99]]
Acc:  0.669  Prec:  0.683  Recall:  0.971  F1: 0.802
SVM
Confusion Matrix : 
[[ 2 44]
 [ 3 99]]
Acc:  0.682  Prec:  0.692  Recall:  0.971  F1: 0.808
Decision Tree
Confusion Matrix : 
[[20 26]
 [33 69]]
Acc:  0.601  Prec:  0.726  Recall:  0.676  F1: 0.701
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[19 27]
 [15 87]]
Acc:  0.716  Prec:  0.763  Recall:  0

In [35]:
arabic_reviews.ex_with_best_k(liwc,classes,liwc.shape[1] if liwc.shape[1] < 100 else 100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
SVM
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
Decision Tree
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
SVM
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
Decision Tree
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689 

Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[ 7 39]
 [10 92]]
Acc:  0.669  Prec:  0.702  Recall:  0.902  F1: 0.79
k = ----------  15
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
SVM
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
Decision Tree
Confusion Matrix : 
[[12 34]
 [34 68]]
Acc:  0.541  Prec:  0.667  Recall:  0.667  F1: 0.667
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[ 5 41]
 [ 9 93]]
Acc:  0.662  Prec:  0.694  Recall:  0.912  F1: 0.788
k = ----------  16
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:

Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[16 30]
 [21 81]]
Acc:  0.655  Prec:  0.73  Recall:  0.794  F1: 0.761
k = ----------  29
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
SVM
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
Decision Tree
Confusion Matrix : 
[[16 30]
 [36 66]]
Acc:  0.554  Prec:  0.688  Recall:  0.647  F1: 0.667
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[11 35]
 [13 89]]
Acc:  0.676  Prec:  0.718  Recall:  0.873  F1: 0.788
k = ----------  30
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:

Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[16 30]
 [25 77]]
Acc:  0.628  Prec:  0.72  Recall:  0.755  F1: 0.737
k = ----------  43
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
SVM
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
Decision Tree
Confusion Matrix : 
[[19 27]
 [36 66]]
Acc:  0.574  Prec:  0.71  Recall:  0.647  F1: 0.677
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
k = ----------  44
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec

 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
Decision Tree
Confusion Matrix : 
[[11 35]
 [29 73]]
Acc:  0.568  Prec:  0.676  Recall:  0.716  F1: 0.695
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[14 32]
 [20 82]]
Acc:  0.649  Prec:  0.719  Recall:  0.804  F1: 0.759
k = ----------  57
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 0 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
SVM
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
Decision Tree
Confusion Matrix : 
[[14 32]
 [27 75]]
Acc:  0.601  Prec:  0.701  Recall:  0.735  F1: 0.718
Random Forest
Confusion Matrix : 
[[  0  46]
 [  0 102]]
Acc:  0.689  Prec:  0.689  Recall:  1.0  F1: 0.816
NN
Confusion Matrix : 
[[10 36]
 [25 77]]
Acc:  0.588  Prec:  0.681  Recall:  0.755  F1: 0.716
k = -----

# Do on all of the data

In [36]:
tf_idf_all = arabic_reviews.extract_tfidf(books_data["review_en"])
struct_all = arabic_reviews.struct_extract(books_data["review_en"])
inq_all = arabic_reviews.inq_extract(books_data["review_en"])
liwc_all = arabic_reviews.liwc_extract(books_data["review_en"].values)
galc_all = arabic_reviews.galc_extract(books_data["review_en"].values)

[nltk_data] Downloading package stopwords to /Users/Omar/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/Omar/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!



Sample feature names identified :  ['-_-', '..and', '..in', '..kan', '..kint', '..la', '..lkn', '..mn', '//www.goodreads.com/review/show', '1', '1.', '10', '100', '15', '150', '18', '19', '1919', '1948', '2', '2.', '2.5', '20', '200', '2008']

Size of TFIDF matrix :  (2404, 4693)


In [37]:
books_data_rt = pd.read_csv("Book_labeled_all_rows_with_ratings.csv")
classes = books_data_rt["ratings_combined"].map(lambda x: "pos_rating" if x == "pos_rating" else "neg_rating")

In [43]:
arabic_reviews.ex_with_best_k(tf_idf_all[0],classes,100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  0  84]
 [  3 154]]
Acc:  0.639  Prec:  0.647  Recall:  0.981  F1: 0.78
Decision Tree
Confusion Matrix : 
[[  0  84]
 [  5 152]]
Acc:  0.631  Prec:  0.644  Recall:  0.968  F1: 0.774
Random Forest
Confusion Matrix : 
[[  0  84]
 [  5 152]]
Acc:  0.631  Prec:  0.644  Recall:  0.968  F1: 0.774
NN
Confusion Matrix : 
[[  0  84]
 [  5 152]]
Acc:  0.631  Prec:  0.644  Recall:  0.968  F1: 0.774
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  0  84]
 [  3 154]]
Acc:  0.639  Prec:  0.647  Recall:  0.981  F1: 0.78
Decision Tree
Confusion Matrix : 
[[  0  84]
 [ 10 147]]
Acc:

Random Forest
Confusion Matrix : 
[[  0  84]
 [  4 153]]
Acc:  0.635  Prec:  0.646  Recall:  0.975  F1: 0.777
NN
Confusion Matrix : 
[[ 16  68]
 [  9 148]]
Acc:  0.68  Prec:  0.685  Recall:  0.943  F1: 0.794
k = ----------  15
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  1  83]
 [  0 157]]
Acc:  0.656  Prec:  0.654  Recall:  1.0  F1: 0.791
SVM
Confusion Matrix : 
[[  2  82]
 [  6 151]]
Acc:  0.635  Prec:  0.648  Recall:  0.962  F1: 0.774
Decision Tree
Confusion Matrix : 
[[ 22  62]
 [ 23 134]]
Acc:  0.647  Prec:  0.684  Recall:  0.854  F1: 0.759
Random Forest
Confusion Matrix : 
[[  0  84]
 [  1 156]]
Acc:  0.647  Prec:  0.65  Recall:  0.994  F1: 0.786
NN
Confusion Matrix : 
[[ 15  69]
 [  9 148]]
Acc:  0.676  Prec:  0.682  Recall:  0.943  F1: 0.791
k = ----------  16
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
A

NN
Confusion Matrix : 
[[ 27  57]
 [ 16 141]]
Acc:  0.697  Prec:  0.712  Recall:  0.898  F1: 0.794
k = ----------  28
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  2  82]
 [  3 154]]
Acc:  0.647  Prec:  0.653  Recall:  0.981  F1: 0.784
Decision Tree
Confusion Matrix : 
[[ 24  60]
 [ 23 134]]
Acc:  0.656  Prec:  0.691  Recall:  0.854  F1: 0.764
Random Forest
Confusion Matrix : 
[[  0  84]
 [  1 156]]
Acc:  0.647  Prec:  0.65  Recall:  0.994  F1: 0.786
NN
Confusion Matrix : 
[[ 27  57]
 [ 16 141]]
Acc:  0.697  Prec:  0.712  Recall:  0.898  F1: 0.794
k = ----------  29
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  2  82]
 [  3 154]]
Acc:  0.647 

Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
k = ----------  42
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  2  82]
 [  0 157]]
Acc:  0.66  Prec:  0.657  Recall:  1.0  F1: 0.793
SVM
Confusion Matrix : 
[[  8  76]
 [  3 154]]
Acc:  0.672  Prec:  0.67  Recall:  0.981  F1: 0.796
Decision Tree
Confusion Matrix : 
[[ 25  59]
 [ 30 127]]
Acc:  0.631  Prec:  0.683  Recall:  0.809  F1: 0.741
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 35  49]
 [ 16 141]]
Acc:  0.73  Prec:  0.742  Recall:  0.898  F1: 0.813
k = ----------  43
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  2  82]
 [  0 157]]
Acc:  0.

NN
Confusion Matrix : 
[[ 34  50]
 [ 25 132]]
Acc:  0.689  Prec:  0.725  Recall:  0.841  F1: 0.779
k = ----------  55
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  3  81]
 [  0 157]]
Acc:  0.664  Prec:  0.66  Recall:  1.0  F1: 0.795
SVM
Confusion Matrix : 
[[ 10  74]
 [  3 154]]
Acc:  0.68  Prec:  0.675  Recall:  0.981  F1: 0.8
Decision Tree
Confusion Matrix : 
[[ 32  52]
 [ 31 126]]
Acc:  0.656  Prec:  0.708  Recall:  0.803  F1: 0.752
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 36  48]
 [ 25 132]]
Acc:  0.697  Prec:  0.733  Recall:  0.841  F1: 0.783
k = ----------  56
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  3  81]
 [  0 157]]
Acc:  0.664  Prec:  0.66  Recall:  1.0  F1: 0.795
SVM
Confusion Matrix : 
[[ 10  74]
 [  3 154]]
Acc:  0.68  Prec: 

Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 35  49]
 [ 23 134]]
Acc:  0.701  Prec:  0.732  Recall:  0.854  F1: 0.788
k = ----------  69
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  4  80]
 [  0 157]]
Acc:  0.668  Prec:  0.662  Recall:  1.0  F1: 0.797
SVM
Confusion Matrix : 
[[ 10  74]
 [  3 154]]
Acc:  0.68  Prec:  0.675  Recall:  0.981  F1: 0.8
Decision Tree
Confusion Matrix : 
[[ 30  54]
 [ 28 129]]
Acc:  0.66  Prec:  0.705  Recall:  0.822  F1: 0.759
Random Forest
Confusion Matrix : 
[[  0  84]
 [  1 156]]
Acc:  0.647  Prec:  0.65  Recall:  0.994  F1: 0.786
NN
Confusion Matrix : 
[[ 39  45]
 [ 27 130]]
Acc:  0.701  Prec:  0.743  Recall:  0.828  F1: 0.783
k = ----------  70
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  4  80]
 [  0 157]]
Acc:  

NN
Confusion Matrix : 
[[ 36  48]
 [ 28 129]]
Acc:  0.685  Prec:  0.729  Recall:  0.822  F1: 0.772
k = ----------  82
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  4  80]
 [  0 157]]
Acc:  0.668  Prec:  0.662  Recall:  1.0  F1: 0.797
SVM
Confusion Matrix : 
[[ 11  73]
 [  4 153]]
Acc:  0.68  Prec:  0.677  Recall:  0.975  F1: 0.799
Decision Tree
Confusion Matrix : 
[[ 31  53]
 [ 33 124]]
Acc:  0.643  Prec:  0.701  Recall:  0.79  F1: 0.743
Random Forest
Confusion Matrix : 
[[  0  84]
 [  1 156]]
Acc:  0.647  Prec:  0.65  Recall:  0.994  F1: 0.786
NN
Confusion Matrix : 
[[ 33  51]
 [ 25 132]]
Acc:  0.685  Prec:  0.721  Recall:  0.841  F1: 0.776
k = ----------  83
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  4  80]
 [  0 157]]
Acc:  0.668  Prec:  0.662  Recall:  1.0  F1: 0.797
SVM
Confusion Matrix : 
[[ 11  73]
 [  4 153]]
Acc:  0.68  Pr

Random Forest
Confusion Matrix : 
[[  0  84]
 [  1 156]]
Acc:  0.647  Prec:  0.65  Recall:  0.994  F1: 0.786
NN
Confusion Matrix : 
[[ 40  44]
 [ 24 133]]
Acc:  0.718  Prec:  0.751  Recall:  0.847  F1: 0.796
k = ----------  96
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  4  80]
 [  0 157]]
Acc:  0.668  Prec:  0.662  Recall:  1.0  F1: 0.797
SVM
Confusion Matrix : 
[[ 11  73]
 [  4 153]]
Acc:  0.68  Prec:  0.677  Recall:  0.975  F1: 0.799
Decision Tree
Confusion Matrix : 
[[ 26  58]
 [ 38 119]]
Acc:  0.602  Prec:  0.672  Recall:  0.758  F1: 0.713
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 37  47]
 [ 32 125]]
Acc:  0.672  Prec:  0.727  Recall:  0.796  F1: 0.76
k = ----------  97
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  5  79]
 [  0 157]]
Acc:

In [39]:
arabic_reviews.ex_with_best_k(struct_all,classes,struct_all.shape[1] if struct_all.shape[1] < 100 else 100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Decision Tree
Confusion Matrix : 
[[  0  84]
 [  2 155]]
Acc:  0.643  Prec:  0.649  Recall:  0.987  F1: 0.783
Random Forest
Confusion Matrix : 
[[  0  84]
 [  1 156]]
Acc:  0.647  Prec:  0.65  Recall:  0.994  F1: 0.786
NN
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Decision Tree
Confusion Matrix : 
[[ 19  65]
 [ 56 101]]
Acc:  0.4

In [40]:
arabic_reviews.ex_with_best_k(inq_all[1:],classes,inq_all.shape[1] if inq_all.shape[1] < 100 else 100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Decision Tree
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Decision Tree
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651 

SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Decision Tree
Confusion Matrix : 
[[ 22  62]
 [ 27 130]]
Acc:  0.631  Prec:  0.677  Recall:  0.828  F1: 0.745
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 21  63]
 [ 17 140]]
Acc:  0.668  Prec:  0.69  Recall:  0.892  F1: 0.778
k = ----------  15
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Decision Tree
Confusion Matrix : 
[[ 23  61]
 [ 27 130]]
Acc:  0.635  Prec:  0.681  Recall:  0.828  F1: 0.747
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 18  66]
 [ 18 139]]
Acc:  0.651 

Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 28  56]
 [ 35 122]]
Acc:  0.622  Prec:  0.685  Recall:  0.777  F1: 0.728
k = ----------  28
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  2  82]
 [  0 157]]
Acc:  0.66  Prec:  0.657  Recall:  1.0  F1: 0.793
SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Decision Tree
Confusion Matrix : 
[[ 28  56]
 [ 43 114]]
Acc:  0.589  Prec:  0.671  Recall:  0.726  F1: 0.697
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 39  45]
 [ 40 117]]
Acc:  0.647  Prec:  0.722  Recall:  0.745  F1: 0.734
k = ----------  29
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  1  83]
 [  0 157]]
Acc:  

NN
Confusion Matrix : 
[[ 37  47]
 [ 43 114]]
Acc:  0.627  Prec:  0.708  Recall:  0.726  F1: 0.717
k = ----------  41
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  3  81]
 [  0 157]]
Acc:  0.664  Prec:  0.66  Recall:  1.0  F1: 0.795
SVM
Confusion Matrix : 
[[  1  83]
 [  0 157]]
Acc:  0.656  Prec:  0.654  Recall:  1.0  F1: 0.791
Decision Tree
Confusion Matrix : 
[[ 35  49]
 [ 53 104]]
Acc:  0.577  Prec:  0.68  Recall:  0.662  F1: 0.671
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 41  43]
 [ 40 117]]
Acc:  0.656  Prec:  0.731  Recall:  0.745  F1: 0.738
k = ----------  42
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  4  80]
 [  0 157]]
Acc:  0.668  Prec:  0.662  Recall:  1.0  F1: 0.797
SVM
Confusion Matrix : 
[[  2  82]
 [  0 157]]
Acc:  0.66  Prec:

SVM
Confusion Matrix : 
[[  5  79]
 [  0 157]]
Acc:  0.672  Prec:  0.665  Recall:  1.0  F1: 0.799
Decision Tree
Confusion Matrix : 
[[ 33  51]
 [ 51 106]]
Acc:  0.577  Prec:  0.675  Recall:  0.675  F1: 0.675
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 29  55]
 [ 28 129]]
Acc:  0.656  Prec:  0.701  Recall:  0.822  F1: 0.757
k = ----------  55
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  4  80]
 [  0 157]]
Acc:  0.668  Prec:  0.662  Recall:  1.0  F1: 0.797
SVM
Confusion Matrix : 
[[  6  78]
 [  0 157]]
Acc:  0.676  Prec:  0.668  Recall:  1.0  F1: 0.801
Decision Tree
Confusion Matrix : 
[[ 38  46]
 [ 57 100]]
Acc:  0.573  Prec:  0.685  Recall:  0.637  F1: 0.66
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 34  50]
 [ 35 122]]
Acc:  0.647 

Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 33  51]
 [ 20 137]]
Acc:  0.705  Prec:  0.729  Recall:  0.873  F1: 0.794
k = ----------  68
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  5  79]
 [  0 157]]
Acc:  0.672  Prec:  0.665  Recall:  1.0  F1: 0.799
SVM
Confusion Matrix : 
[[  9  75]
 [  0 157]]
Acc:  0.689  Prec:  0.677  Recall:  1.0  F1: 0.807
Decision Tree
Confusion Matrix : 
[[ 32  52]
 [ 55 102]]
Acc:  0.556  Prec:  0.662  Recall:  0.65  F1: 0.656
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
k = ----------  69
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  5  79]
 [  0 157]]
Acc:  0.

NN
Confusion Matrix : 
[[ 35  49]
 [ 27 130]]
Acc:  0.685  Prec:  0.726  Recall:  0.828  F1: 0.774
k = ----------  81
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  5  79]
 [  0 157]]
Acc:  0.672  Prec:  0.665  Recall:  1.0  F1: 0.799
SVM
Confusion Matrix : 
[[ 12  72]
 [  0 157]]
Acc:  0.701  Prec:  0.686  Recall:  1.0  F1: 0.813
Decision Tree
Confusion Matrix : 
[[ 37  47]
 [ 52 105]]
Acc:  0.589  Prec:  0.691  Recall:  0.669  F1: 0.68
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 36  48]
 [ 40 117]]
Acc:  0.635  Prec:  0.709  Recall:  0.745  F1: 0.727
k = ----------  82
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  5  79]
 [  0 157]]
Acc:  0.672  Prec:  0.665  Recall:  1.0  F1: 0.799
SVM
Confusion Matrix : 
[[ 12  72]
 [  0 157]]
Acc:  0.701  Pre

SVM
Confusion Matrix : 
[[ 12  72]
 [  0 157]]
Acc:  0.701  Prec:  0.686  Recall:  1.0  F1: 0.813
Decision Tree
Confusion Matrix : 
[[37 47]
 [58 99]]
Acc:  0.564  Prec:  0.678  Recall:  0.631  F1: 0.653
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 29  55]
 [ 29 128]]
Acc:  0.651  Prec:  0.699  Recall:  0.815  F1: 0.753
k = ----------  95
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  4  80]
 [  0 157]]
Acc:  0.668  Prec:  0.662  Recall:  1.0  F1: 0.797
SVM
Confusion Matrix : 
[[ 12  72]
 [  0 157]]
Acc:  0.701  Prec:  0.686  Recall:  1.0  F1: 0.813
Decision Tree
Confusion Matrix : 
[[ 38  46]
 [ 53 104]]
Acc:  0.589  Prec:  0.693  Recall:  0.662  F1: 0.678
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 32  52]
 [ 38 119]]
Acc:  0.627  Pr

In [41]:
arabic_reviews.ex_with_best_k(liwc_all,classes,liwc_all.shape[1] if liwc_all.shape[1] < 100 else 100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Decision Tree
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Decision Tree
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651 

SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Decision Tree
Confusion Matrix : 
[[ 27  57]
 [ 50 107]]
Acc:  0.556  Prec:  0.652  Recall:  0.682  F1: 0.667
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 26  58]
 [ 21 136]]
Acc:  0.672  Prec:  0.701  Recall:  0.866  F1: 0.775
k = ----------  15
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Decision Tree
Confusion Matrix : 
[[ 34  50]
 [ 46 111]]
Acc:  0.602  Prec:  0.689  Recall:  0.707  F1: 0.698
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 12  72]
 [ 15 142]]
Acc:  0.639

Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 33  51]
 [ 30 127]]
Acc:  0.664  Prec:  0.713  Recall:  0.809  F1: 0.758
k = ----------  28
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Decision Tree
Confusion Matrix : 
[[ 29  55]
 [ 44 113]]
Acc:  0.589  Prec:  0.673  Recall:  0.72  F1: 0.695
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 26  58]
 [ 21 136]]
Acc:  0.672  Prec:  0.701  Recall:  0.866  F1: 0.775
k = ----------  29
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  

NN
Confusion Matrix : 
[[ 24  60]
 [ 33 124]]
Acc:  0.614  Prec:  0.674  Recall:  0.79  F1: 0.727
k = ----------  41
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Decision Tree
Confusion Matrix : 
[[ 27  57]
 [ 49 108]]
Acc:  0.56  Prec:  0.655  Recall:  0.688  F1: 0.671
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 33  51]
 [ 41 116]]
Acc:  0.618  Prec:  0.695  Recall:  0.739  F1: 0.716
k = ----------  42
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec

SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Decision Tree
Confusion Matrix : 
[[ 32  52]
 [ 47 110]]
Acc:  0.589  Prec:  0.679  Recall:  0.701  F1: 0.69
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
k = ----------  55
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Decision Tree
Confusion Matrix : 
[[ 31  53]
 [ 42 115]]
Acc:  0.606  Prec:  0.685  Recall:  0.732  F1: 0.708
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 32  52]
 [ 29 128]]
Acc:  0.664  P

In [42]:
arabic_reviews.ex_with_best_k(galc_all,classes,galc_all.shape[1] if galc_all.shape[1] < 100 else 100)

k = ----------  1
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Decision Tree
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
k = ----------  2
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
SVM
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
Decision Tree
Confusion Matrix : 
[[  1  83]
 [  1 156]]
Acc:  0.651 

SVM
Confusion Matrix : 
[[  5  79]
 [  3 154]]
Acc:  0.66  Prec:  0.661  Recall:  0.981  F1: 0.79
Decision Tree
Confusion Matrix : 
[[ 14  70]
 [ 13 144]]
Acc:  0.656  Prec:  0.673  Recall:  0.917  F1: 0.776
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 14  70]
 [ 11 146]]
Acc:  0.664  Prec:  0.676  Recall:  0.93  F1: 0.783
k = ----------  15
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  4  80]
 [  2 155]]
Acc:  0.66  Prec:  0.66  Recall:  0.987  F1: 0.791
SVM
Confusion Matrix : 
[[  6  78]
 [  6 151]]
Acc:  0.651  Prec:  0.659  Recall:  0.962  F1: 0.782
Decision Tree
Confusion Matrix : 
[[ 14  70]
 [ 13 144]]
Acc:  0.656  Prec:  0.673  Recall:  0.917  F1: 0.776
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 13  71]
 [ 12 145]]
Acc:  0.65

Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 10  74]
 [ 13 144]]
Acc:  0.639  Prec:  0.661  Recall:  0.917  F1: 0.768
k = ----------  28
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  4  80]
 [  2 155]]
Acc:  0.66  Prec:  0.66  Recall:  0.987  F1: 0.791
SVM
Confusion Matrix : 
[[  5  79]
 [  4 153]]
Acc:  0.656  Prec:  0.659  Recall:  0.975  F1: 0.787
Decision Tree
Confusion Matrix : 
[[ 15  69]
 [ 16 141]]
Acc:  0.647  Prec:  0.671  Recall:  0.898  F1: 0.768
Random Forest
Confusion Matrix : 
[[  0  84]
 [  0 157]]
Acc:  0.651  Prec:  0.651  Recall:  1.0  F1: 0.789
NN
Confusion Matrix : 
[[ 14  70]
 [ 15 142]]
Acc:  0.647  Prec:  0.67  Recall:  0.904  F1: 0.77
k = ----------  29
Classes found :  ['neg_rating' 'pos_rating']

Classes converted to integers : [1 1 0 ... 1 1 1]
NB
Confusion Matrix : 
[[  4  80]
 [  2 155]]
Acc: 

In [47]:
arabic_reviews.top_words(tf_idf_all[1],tf_idf_all[0],classes,92,"star_ratings_arabic_books_top_words.csv")

[('boring', 14.241643976380667),
 ('wonderful', 11.932056956833653),
 ('weak', 7.752197634455159),
 ('article', 7.213715561684015),
 ('good', 7.172011844203123),
 ('hype', 7.058322931660299),
 ('bad', 7.012571848596723),
 ('idea', 6.921246071828335),
 ('disappointing', 5.86144535902838),
 ('-_-', 5.5939882522381055),
 ('star', 5.441789068178665),
 ('painful', 5.357799919488478),
 ('silly', 5.086820705510094),
 ('somewhat', 4.774705780072198),
 ('uproar', 4.634074714307728),
 ('unfortunately', 4.600485617899579),
 ('superficial', 4.414970442266286),
 ('nothing', 4.155365486261125),
 ('content', 4.144173742889959),
 ('stupid', 4.10243197459967),
 ('ordinary', 4.040400625085944),
 ('fantastic', 3.9598183599237506),
 ('hmam', 3.905627034573512),
 ('naive', 3.8319543681513792),
 ('repetition', 3.8128834451313685),
 ('general', 3.7837924235229785),
 ('expectation', 3.711867625862202),
 ('language', 3.685773534329311),
 ('prosaic', 3.634753482910988),
 ('mahbthash', 3.537280699589077),
 ('lac